---
# =============================================================================
# FortiGate DHCP Reserved Address Delete Execute For Workflow Playbook v5.0
# 用途：執行MAC刪除，將配置還原為Reserved狀態，使用FortiOS模塊優化
# 輸入：接收Preview的workflow變數
# 輸出：執行結果和摘要，包括還原機制
# =============================================================================

- name: FortiGate DHCP Delete Execute For Workflow v5.0
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    processed_configs: "{{ (wf_processed_configs | default('[]')) | from_json }}"
    dhcp_server_id: "{{ wf_server_id }}"
    fortigate_host: "{{ fortigate_host }}"
    fortigate_access_token: "{{ fortigate_access_token }}"
    validate_certs: "{{ fortigate_validate_certs | default(true) | bool }}"

  tasks:
    - name: "⏰ Record Start Time"
      ansible.builtin.set_fact:
        execution_start_time: "{{ ansible_date_time.epoch | int }}"

    - name: "🔍 Validate Workflow Parameters"
      ansible.builtin.fail:
        msg: "缺少Workflow參數"
      when: processed_configs | length == 0

    - name: "🔌 Test FortiGate Connection"
      fortinet.fortios.fortios_monitor_fact:
        access_token: "{{ fortigate_access_token }}"
        vdom: "{{ wf_vdom_name | default('root') }}"
        selector: "system_global"
      register: api_test

    - name: "🔍 Pre-execution Verification"
      fortinet.fortios.fortios_system_dhcp_server:
        access_token: "{{ fortigate_access_token }}"
        vdom: "{{ wf_vdom_name }}"
        state: gather
        system_dhcp_server:
          id: "{{ dhcp_server_id }}"
      register: pre_config

    - name: "🔧 Execute Updates"
      fortinet.fortios.fortios_system_dhcp_server:
        access_token: "{{ fortigate_access_token }}"
        vdom: "{{ wf_vdom_name }}"
        state: present
        system_dhcp_server:
          id: "{{ dhcp_server_id }}"
          reserved_address:
            - id: "{{ item.id }}"
              ip: "{{ item.ip }}"
              mac: "{{ item.reserved_mac }}"
              description: "Reserved"
      loop: "{{ processed_configs }}"
      when: not item.already_reserved
      register: update_results

    - name: "🔍 Post-execution Verification"
      fortinet.fortios.fortios_system_dhcp_server:
        access_token: "{{ fortigate_access_token }}"
        vdom: "{{ wf_vdom_name }}"
        state: gather
        system_dhcp_server:
          id: "{{ dhcp_server_id }}"
      register: post_config
      when: update_results.changed

    - name: "❌ Rollback on Failure"
      fortinet.fortios.fortios_config:
        access_token: "{{ fortigate_access_token }}"
        vdom: "{{ wf_vdom_name }}"
        config: "restore"
        backup_path: "{{ fortigate_backup_path }}/dhcp_preview_backup_{{ execution_start_time }}.conf"
      when: update_results.failed | default(false)

    - name: "📊 Execution Summary"
      ansible.builtin.debug:
        msg: "✅ 執行完成 | 變更數: {{ update_results.changed | length }}"

    - name: "⏱️ Time Summary"
      ansible.builtin.set_fact:
        execution_time: "{{ (ansible_date_time.epoch | int) - execution_start_time }}"
      ansible.builtin.debug:
        msg: "⏱️ 用時: {{ execution_time }}s"
