---
# =============================================================================
# FortiGate DHCP Reserved Address Delete Preview For Workflow Playbook v5.0
# 用途：預覽要刪除的MAC配置，計算還原後的MAC地址，使用FortiOS模塊優化
# 輸出：顯示當前配置和預計變更內容，設定workflow變數，包括表格輸出
# =============================================================================

- name: FortiGate DHCP Delete Preview For Workflow v5.0
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    target_mac_list: "{{ delete_mac_param.split(',') | map('trim') | list }}"  # 支援批次MAC
    target_dhcp_server_id: "{{ server_id | default('3') }}"
    api_retries: "{{ fortigate_api_retries | default('3') | int }}"
    api_delay: "{{ fortigate_api_delay | default('5') | int }}"
    backup_enabled: "{{ fortigate_backup_enabled | default(true) | bool }}"
    connection_timeout: "{{ fortigate_timeout | default('30') | int }}"
    validate_certs: "{{ fortigate_validate_certs | default(true) | bool }}"  # 預設true

  tasks:
    - name: "⏰ Record Start Time"
      ansible.builtin.set_fact:
        preview_start_time: "{{ ansible_date_time.epoch | int }}"

    - name: "🔍 Validate Credentials"
      ansible.builtin.fail:
        msg: "缺少FortiGate Credential參數"
      when: fortigate_host is not defined or fortigate_access_token is not defined

    - name: "🔍 Validate MAC Format"
      ansible.builtin.set_fact:
        normalized_macs: "{{ target_mac_list | map('regex_replace', '-', ':') | map('lower') | list }}"
        valid_macs: "{{ normalized_macs | map('regex_search', '^([0-9a-fa-f]{2}:){5}[0-9a-fa-f]{2}$') | select('defined') | list }}"
      failed_when: normalized_macs | length != valid_macs | length

    - name: "🔌 Test FortiGate Connection"
      fortinet.fortios.fortios_monitor_fact:
        access_token: "{{ fortigate_access_token }}"
        vdom: "{{ fortigate_vdom | default('root') }}"
        selector: "system_global"
      register: api_test

    - name: "✅ API Connection Status"
      ansible.builtin.debug:
        msg: "✅ API連線成功 | FortiGate版本: {{ api_test.facts.version | default('未知') }}"

    - name: "🔍 Get Current DHCP Reservations"
      fortinet.fortios.fortios_system_dhcp_server:
        access_token: "{{ fortigate_access_token }}"
        vdom: "{{ fortigate_vdom }}"
        state: gather
        system_dhcp_server:
          id: "{{ target_dhcp_server_id }}"
      register: existing_reservations

    - name: "💾 Backup Configuration"
      fortinet.fortios.fortios_config:
        access_token: "{{ fortigate_access_token }}"
        vdom: "{{ fortigate_vdom }}"
        config: "backup"
        backup_path: "{{ fortigate_backup_path | default('/tmp') }}"
        backup_filename: "dhcp_preview_backup_{{ ansible_date_time.epoch }}.conf"
      when: backup_enabled

    - name: "🧮 Process Each MAC"
      ansible.builtin.set_fact:
        processed_configs: "{{ processed_configs | default([]) + [item] }}"
      loop: "{{ normalized_macs }}"
      vars:
        target_object: "{{ existing_reservations.system_dhcp_server.reserved_address | selectattr('mac', 'equalto', item) | first | default(none) }}"
      when: target_object is defined
      with_items:
        - id: "{{ target_object.id }}"
          ip: "{{ target_object.ip }}"
          original_mac: "{{ target_object.mac }}"
          original_desc: "{{ target_object.description | default('') }}"
          ip_fourth_octet: "{{ target_object.ip.split('.')[-1] | int }}"
          first_digit: "{{ target_object.ip.split('.')[-1][0] if target_object.ip.split('.')[-1] | length == 3 else '0' }}"  # 處理<100
          last_two_digits: "{{ target_object.ip.split('.')[-1][1:] if target_object.ip.split('.')[-1] | length == 3 else (target_object.ip.split('.')[-1] | int).to_string.zfill(2) }}"
          reserved_mac: "ff:ff:ff:ff:f{{ first_digit }}:{{ last_two_digits }}"
          already_reserved: "{{ target_object.mac.lower() == reserved_mac and target_object.description | default('') | lower == 'reserved' }}"
          ip_range_valid: "{{ ip_fourth_octet >= 100 and ip_fourth_octet <= 250 }}"

    - name: "📊 Generate Preview Table"
      ansible.builtin.template:
        src: preview_table.j2  # 假設有Jinja模板生成Markdown表格
        dest: "/tmp/preview_table.md"
      vars:
        configs: "{{ processed_configs }}"

    - name: "📤 Set Workflow Variables"
      ansible.builtin.set_stats:
        data:
          wf_processed_configs: "{{ processed_configs | to_json }}"
          wf_server_id: "{{ target_dhcp_server_id }}"
          wf_backup_info: "{{ backup_info | default({}) | to_json }}"
          wf_preview_version: "v5.0"

    - name: "🎯 Preview Complete"
      ansible.builtin.debug:
        msg: "🎯 預覽完成 | 等待確認"
