---
# =============================================================================
# FortiGate DHCP Reserved Address Delete + Firewall Address Delete Preview v5.1
# 用途：預覽要刪除的MAC配置（DHCP + Firewall Address）
# 功能：1. DHCP MAC還原為Reserved 2. Firewall Address從Group移除並刪除
# 修正：處理FortiGate API中macaddr為list類型的問題
# 輸出：顯示DHCP和Firewall兩個功能的變更預覽，設定workflow變數
# =============================================================================

- name: FortiGate DHCP + Firewall Delete Preview For Workflow v5.1
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    # Survey 參數
    target_mac: "{{ delete_mac_param }}"
    target_dhcp_server_id: "{{ server_id | default('3') }}"
    
    # Server ID 對應關係
    server_mapping:
      "2":
        dhcp_description: "vlan40_PC"
        address_group: "Group_40_PC-Allow-MAC"
      "12":
        dhcp_description: "vlan22_FIC_WAN"  
        address_group: "Group_22_FIC_Allow-MAC"
    
    # API 連接參數
    api_retries: "{{ fortigate_api_retries | default('3') | int }}"
    api_delay: "{{ fortigate_api_delay | default('5') | int }}"
    backup_enabled: "{{ fortigate_backup_enabled | default(true) | bool }}"
    connection_timeout: "{{ fortigate_timeout | default('30') | int }}"
    validate_certs: "{{ fortigate_validate_certs | default(false) | bool }}"
    
  tasks:
    # 記錄開始時間
    - name: "⏰ Record Start Time"
      ansible.builtin.set_fact:
        preview_start_time: "{{ ansible_date_time.epoch | int }}"

    # 參數驗證
    - name: "🔍 Validate Credentials"
      ansible.builtin.fail:
        msg: "缺少FortiGate Credential參數: {{ missing_params | join(', ') }}"
      vars:
        required_params:
          - fortigate_host
          - fortigate_access_token
        missing_params: "{{ required_params | select('undefined') | list }}"
      when: 
        - fortigate_host is not defined or 
          fortigate_access_token is not defined

    # Survey參數驗證
    - name: "🔍 Validate Survey Parameters"
      ansible.builtin.fail:
        msg: "缺少Survey參數: {{ missing_survey_params | join(', ') }}"
      vars:
        required_survey_params:
          - delete_mac_param
          - server_id
        missing_survey_params: "{{ required_survey_params | select('undefined') | list }}"
      when: delete_mac_param is not defined or server_id is not defined

    # Server ID 驗證
    - name: "🔍 Validate Server ID"
      ansible.builtin.fail:
        msg: "不支援的DHCP Server ID: {{ target_dhcp_server_id }}。支援的ID: {{ server_mapping.keys() | list | join(', ') }}"
      when: target_dhcp_server_id not in server_mapping

    # 設定Server對應資訊
    - name: "🔧 Set Server Mapping Info"
      ansible.builtin.set_fact:
        server_info: "{{ server_mapping[target_dhcp_server_id] }}"
        target_address_group: "{{ server_mapping[target_dhcp_server_id].address_group }}"

    # MAC格式驗證
    - name: "🔍 Validate MAC Address Format"
      ansible.builtin.set_fact:
        mac_valid: "{{ target_mac | regex_search('^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$') is not none }}"

    - name: "❌ Invalid MAC Format"
      ansible.builtin.fail:
        msg: "MAC地址格式錯誤: {{ target_mac }}。正確格式: xx:xx:xx:xx:xx:xx 或 xx-xx-xx-xx-xx-xx"
      when: not mac_valid

    # 正規化MAC地址格式
    - name: "🔧 Normalize MAC Address"
      ansible.builtin.set_fact:
        normalized_mac: "{{ target_mac | replace('-', ':') | lower }}"

    # API連線測試
    - name: "🔌 Test FortiGate API Connection"
      ansible.builtin.uri:
        url: "https://{{ fortigate_host }}/api/v2/cmdb/system/global"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        validate_certs: "{{ validate_certs }}"
        status_code: 200
        timeout: "{{ connection_timeout }}"
      register: api_test
      retries: "{{ api_retries }}"
      delay: "{{ api_delay }}"

    # FortiGate版本取得
    - name: "✅ API Connection Status"
      ansible.builtin.debug:
        msg: "✅ API連線成功 | FortiGate版本: {{ fortigate_version }}"
      vars:
        fortigate_version: "{{ api_test.json.results.version | default(api_test.json.version | default('未知')) }}"

    # 顯示預覽參數
    - name: "📋 FortiGate DHCP + Firewall Delete Preview v5.1"
      ansible.builtin.debug:
        msg: "===========================================" 

    - name: "📋 Preview Parameters"
      ansible.builtin.debug:
        msg: "🔍 整合預覽模式 | 目標MAC: {{ normalized_mac }} | DHCP Server: {{ target_dhcp_server_id }} ({{ server_info.dhcp_description }}) | Address Group: {{ target_address_group }} | Host: {{ fortigate_host }}"

    # ==================== DHCP 功能預覽 ====================
    - name: "📊 DHCP Preview Section"
      ansible.builtin.debug:
        msg: "==================== DHCP 預覽 ===================="

    # 獲取DHCP配置
    - name: "🔍 Get Current DHCP Reserved Addresses"
      ansible.builtin.uri:
        url: "https://{{ fortigate_host }}/api/v2/cmdb/system.dhcp/server/{{ target_dhcp_server_id }}/reserved-address"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        validate_certs: "{{ validate_certs }}"
        status_code: 200
        timeout: "{{ connection_timeout }}"
      register: existing_reservations
      retries: "{{ api_retries }}"
      delay: "{{ api_delay }}"

    # 搜尋DHCP目標MAC
    - name: "🔍 Search for Target MAC in DHCP"
      ansible.builtin.set_fact:
        dhcp_target_object: "{{ item }}"
      loop: "{{ existing_reservations.json.results }}"
      when:
        - dhcp_target_object is not defined
        - item.mac.lower() == normalized_mac

    # DHCP MAC未找到的處理
    - name: "⚠️ DHCP Target MAC Not Found"
      ansible.builtin.debug:
        msg: "⚠️ DHCP中未找到MAC: {{ normalized_mac }}，將跳過DHCP操作"
      when: dhcp_target_object is not defined

    # DHCP預覽結果
    - name: "📊 DHCP Current Configuration"
      ansible.builtin.debug:
        msg: "📊 DHCP當前 | ID: {{ dhcp_target_object.id }} | IP: {{ dhcp_target_object.ip }} | MAC: {{ dhcp_target_object.mac }} | 描述: {{ dhcp_target_object.description | default('空白') }}"
      when: dhcp_target_object is defined

    # 計算DHCP還原MAC
    - name: "🧮 Calculate DHCP Reserved MAC"
      ansible.builtin.set_fact:
        ip_fourth_octet: "{{ dhcp_target_object.ip.split('.')[3] }}"
        first_digit: "{{ dhcp_target_object.ip.split('.')[3][0] }}"
        last_two_digits: "{{ dhcp_target_object.ip.split('.')[3][1:] }}"
        dhcp_reserved_mac: "ff:ff:ff:ff:f{{ dhcp_target_object.ip.split('.')[3][0] }}:{{ dhcp_target_object.ip.split('.')[3][1:] }}"
      when: dhcp_target_object is defined

    - name: "🔄 DHCP After Delete Configuration" 
      ansible.builtin.debug:
        msg: "🔄 DHCP還原 | ID: {{ dhcp_target_object.id }} | IP: {{ dhcp_target_object.ip }} | MAC: {{ dhcp_reserved_mac }} | 描述: Reserved"
      when: dhcp_target_object is defined

    # ==================== Firewall 功能預覽 ====================
    - name: "🔥 Firewall Preview Section"
      ansible.builtin.debug:
        msg: "==================== Firewall 預覽 ===================="

    # 獲取所有MAC類型的Address
    - name: "🔍 Get All MAC Type Firewall Addresses"
      ansible.builtin.uri:
        url: "https://{{ fortigate_host }}/api/v2/cmdb/firewall/address?filter=type==mac"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        validate_certs: "{{ validate_certs }}"
        status_code: 200
        timeout: "{{ connection_timeout }}"
      register: firewall_addresses
      retries: "{{ api_retries }}"
      delay: "{{ api_delay }}"

    # 顯示Firewall Addresses調試資訊
    - name: "🔍 Debug Firewall Addresses Structure"
      ansible.builtin.debug:
        msg: "🔍 調試 | Address數量: {{ firewall_addresses.json.results | length }} | 第一個Address結構: {{ firewall_addresses.json.results[0] | default('無資料') }}"
      when: firewall_addresses.json.results | length > 0

    # 搜尋目標MAC對應的Address Object（修正版）
    - name: "🔍 Search for Target MAC in Firewall Addresses"
      ansible.builtin.set_fact:
        firewall_target_object: "{{ item }}"
        found_macaddr: "{{ actual_macaddr }}"
      loop: "{{ firewall_addresses.json.results }}"
      vars:
        # 處理macaddr可能是字串或列表的情況
        actual_macaddr: "{{ item.macaddr if item.macaddr is string else (item.macaddr | first if item.macaddr | length > 0 else '') }}"
      when:
        - firewall_target_object is not defined
        - item.name is defined
        - item.name.startswith('MAC_')
        - item.macaddr is defined
        - actual_macaddr | lower == normalized_mac

    # Firewall Address未找到的處理
    - name: "⚠️ Firewall Target Address Not Found"
      ansible.builtin.debug:
        msg: "⚠️ Firewall中未找到MAC: {{ normalized_mac }} 對應的Address Object（名稱需以MAC_開頭），將跳過Firewall操作"
      when: firewall_target_object is not defined

    # 顯示所有MAC_開頭的Address以供調試
    - name: "🔍 List All MAC_ Addresses for Debug"
      ansible.builtin.debug:
        msg: "🔍 MAC_地址 {{ ansible_loop.index }}/{{ mac_addresses | length }} | Name: {{ item.name }} | MAC: {{ actual_mac }} | Type: {{ item.type }}"
      loop: "{{ mac_addresses }}"
      loop_control:
        extended: true
      vars:
        mac_addresses: "{{ firewall_addresses.json.results | selectattr('name', 'defined') | selectattr('name', 'match', '^MAC_.*') | list }}"
        actual_mac: "{{ item.macaddr if item.macaddr is string else (item.macaddr | first if item.macaddr | length > 0 else 'N/A') }}"
      when: 
        - firewall_target_object is not defined
        - mac_addresses | length > 0

    # Firewall Address找到時的預覽
    - name: "📊 Firewall Target Address Found"
      ansible.builtin.debug:
        msg: "📊 Firewall目標 | Name: {{ firewall_target_object.name }} | MAC: {{ found_macaddr }} | Comment: {{ firewall_target_object.comment | default('無') }}"
      when: firewall_target_object is defined

    # 獲取Address Group配置
    - name: "🔍 Get Address Group Configuration"
      ansible.builtin.uri:
        url: "https://{{ fortigate_host }}/api/v2/cmdb/firewall/addrgrp/{{ target_address_group }}"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        validate_certs: "{{ validate_certs }}"
        status_code: 200
        timeout: "{{ connection_timeout }}"
      register: address_group_config
      retries: "{{ api_retries }}"
      delay: "{{ api_delay }}"
      when: firewall_target_object is defined

    # 檢查Address是否在Group中
    - name: "🔍 Check Address in Group"
      ansible.builtin.set_fact:
        address_in_group: "{{ firewall_target_object.name in address_group_config.json.results.member }}"
        original_group_members: "{{ address_group_config.json.results.member }}"
        updated_group_members: "{{ address_group_config.json.results.member | difference([firewall_target_object.name]) }}"
      when: 
        - firewall_target_object is defined
        - address_group_config is defined

    - name: "📊 Address Group Current Status"
      ansible.builtin.debug:
        msg: "📊 Address Group | 名稱: {{ target_address_group }} | 目標Address在Group中: {{ 'YES' if address_in_group else 'NO' }} | 當前Members數: {{ original_group_members | length }}"
      when: firewall_target_object is defined

    - name: "🔄 Address Group After Remove"
      ansible.builtin.debug:
        msg: "🔄 移除後 | Group: {{ target_address_group }} | 移除Member: {{ firewall_target_object.name }} | 剩餘Members數: {{ updated_group_members | length }}"
      when: 
        - firewall_target_object is defined
        - address_in_group

    # ==================== 整合預覽總結 ====================
    - name: "📊 Integrated Preview Summary"
      ansible.builtin.debug:
        msg: "==================== 整合預覽總結 ===================="

    - name: "📊 Operations Summary"
      ansible.builtin.debug:
        msg: "📊 操作總覽 | DHCP操作: {{ 'YES' if dhcp_target_object is defined else 'SKIP' }} | Firewall操作: {{ 'YES' if firewall_target_object is defined else 'SKIP' }} | Address在Group中: {{ 'YES' if (firewall_target_object is defined and address_in_group) else 'NO' }}"

    # 記錄原始配置備份
    - name: "💾 Record Original Configuration for Backup"
      ansible.builtin.set_fact:
        integrated_backup_info:
          timestamp: "{{ ansible_date_time.iso8601 }}"
          dhcp_config: "{{ dhcp_target_object | default({}) }}"
          firewall_config: "{{ firewall_target_object | default({}) }}"
          address_group_config:
            name: "{{ target_address_group }}"
            original_members: "{{ original_group_members | default([]) }}"
            updated_members: "{{ updated_group_members | default([]) }}"
          server_info: "{{ server_info }}"
          purpose: "記錄DHCP和Firewall變更前的原始配置"
      when: backup_enabled

    # 計算預覽時間
    - name: "⏱️ Calculate Preview Time"
      ansible.builtin.set_fact:
        current_time: "{{ ansible_date_time.epoch | int }}"
        preview_time_used: "{{ (ansible_date_time.epoch | int) - (preview_start_time | int) }}"

    - name: "⏱️ Preview Time Summary"
      ansible.builtin.debug:
        msg: "⏱️ 預覽用時: {{ preview_time_used }}s"

    # 最終警告
    - name: "⚠️ Configuration Change Warning"
      ansible.builtin.debug:
        msg: "⚠️ 警告：此操作將永久修改FortiGate的DHCP和Firewall配置！請在Approval Node中仔細確認後再批准執行。"

    # 設定workflow變數（整合版）
    - name: "📤 Set Integrated Workflow Variables"
      ansible.builtin.set_stats:
        data:
          # DHCP 相關變數
          wf_dhcp_enabled: "{{ dhcp_target_object is defined }}"
          wf_dhcp_target_id: "{{ dhcp_target_object.id | default('') }}"
          wf_dhcp_target_ip: "{{ dhcp_target_object.ip | default('') }}"
          wf_dhcp_original_mac: "{{ dhcp_target_object.mac | default('') }}"
          wf_dhcp_reserved_mac: "{{ dhcp_reserved_mac | default('') }}"
          wf_dhcp_original_desc: "{{ dhcp_target_object.description | default('') }}"
          wf_ip_fourth_octet: "{{ ip_fourth_octet | default('') }}"
          wf_first_digit: "{{ first_digit | default('') }}"
          wf_last_two_digits: "{{ last_two_digits | default('') }}"
          # Firewall 相關變數
          wf_firewall_enabled: "{{ firewall_target_object is defined }}"
          wf_firewall_address_name: "{{ firewall_target_object.name | default('') }}"
          wf_firewall_address_mac: "{{ found_macaddr | default('') }}"
          wf_firewall_address_comment: "{{ firewall_target_object.comment | default('') }}"
          wf_address_group_name: "{{ target_address_group }}"
          wf_address_in_group: "{{ address_in_group | default(false) }}"
          wf_original_group_members: "{{ original_group_members | default([]) | to_json }}"
          wf_updated_group_members: "{{ updated_group_members | default([]) | to_json }}"
          # 共用變數
          wf_server_id: "{{ target_dhcp_server_id }}"
          wf_delete_mac: "{{ normalized_mac }}"
          wf_server_info: "{{ server_info | to_json }}"
          wf_backup_info: "{{ integrated_backup_info | default({}) | to_json }}"
          wf_vdom_name: "{{ fortigate_vdom | default('root') }}"
          wf_preview_version: "v5.1"

    - name: "🎯 Integrated Preview Complete"
      ansible.builtin.debug:
        msg: "🎯 整合預覽完成 | 等待人工確認 | MAC {{ normalized_mac }} | DHCP: {{ 'YES' if dhcp_target_object is defined else 'SKIP' }} | Firewall: {{ 'YES' if firewall_target_object is defined else 'SKIP' }} | 版本: v5.1"
