---
# =============================================================================
# FortiGate DHCP Reserved Address Delete Preview For Workflow Playbook
# 用途：預覽要刪除的MAC配置，計算還原後的MAC地址
# 輸出：顯示當前配置和預計變更內容，設定workflow變數
# =============================================================================

- name: FortiGate DHCP Delete Preview For Workflow v3.4
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    delete_mac: "{{ delete_mac_param }}"
    dhcp_server_id: "{{ server_id | default('3') }}"
    fortigate_host: "{{ fortigate_host }}"
    fortigate_token: "{{ fortigate_access_token }}"
    vdom_name: "{{ fortigate_vdom | default('root') }}"
    
  tasks:
    # 參數驗證
    - name: "🔍 Validate Credentials"
      ansible.builtin.fail:
        msg: "缺少FortiGate Credential參數"
      when: fortigate_host is not defined or fortigate_token is not defined

    # 顯示預覽參數（單行格式）
    - name: "📋 FortiGate DHCP Delete Preview v3.4"
      ansible.builtin.debug:
        msg: "===========================================" 

    - name: "📋 Preview Parameters"
      ansible.builtin.debug:
        msg: "🔍 預覽模式 | 目標MAC: {{ delete_mac }} | DHCP Server: {{ dhcp_server_id }} | Host: {{ fortigate_host }}"

    # 獲取DHCP配置
    - name: "🔍 Get Current DHCP Reserved Addresses"
      ansible.builtin.uri:
        url: "https://{{ fortigate_host }}/api/v2/cmdb/system.dhcp/server/{{ dhcp_server_id }}/reserved-address"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_token }}"
        validate_certs: false
        status_code: 200
      register: existing_reservations

    # 顯示當前配置（使用loop逐行顯示）
    - name: "📊 Current DHCP Server {{ dhcp_server_id }} Configurations"
      ansible.builtin.debug:
        msg: "📋 當前配置 {{ ansible_loop.index }}/{{ existing_reservations.json.results | length }} - ID: {{ item.id }} | IP: {{ item.ip }} | MAC: {{ item.mac }} | 描述: {{ item.description | default('無') }}"
      loop: "{{ existing_reservations.json.results }}"
      loop_control:
        extended: true
      when: existing_reservations.json.results | length > 0

    - name: "📊 No Configurations Found"
      ansible.builtin.debug:
        msg: "⚠️ DHCP Server {{ dhcp_server_id }} 目前沒有任何reserved-address配置"
      when: existing_reservations.json.results | length == 0

    # 搜尋目標MAC
    - name: "🔍 Search for Target MAC"
      ansible.builtin.set_fact:
        target_object: "{{ item }}"
      loop: "{{ existing_reservations.json.results }}"
      when:
        - target_object is not defined
        - item.mac.lower() == delete_mac.lower()

    # MAC未找到時的錯誤處理
    - name: "❌ Target MAC Not Found"
      ansible.builtin.debug:
        msg: "❌ 未找到MAC: {{ delete_mac }} 在DHCP Server {{ dhcp_server_id }} 中"
      when: target_object is not defined

    - name: "❌ Available MAC Addresses"
      ansible.builtin.debug:
        msg: "📋 可用MAC {{ ansible_loop.index }}/{{ existing_reservations.json.results | length }} - {{ item.mac }} (IP: {{ item.ip }})"
      loop: "{{ existing_reservations.json.results }}"
      loop_control:
        extended: true
      when: 
        - target_object is not defined
        - existing_reservations.json.results | length > 0

    - name: "❌ Stop Execution - MAC Not Found"
      ansible.builtin.fail:
        msg: "操作終止：未找到指定的MAC地址 {{ delete_mac }}"
      when: target_object is not defined

    # 計算還原MAC
    - name: "🧮 Calculate Reserved MAC Address"
      ansible.builtin.set_fact:
        ip_fourth_octet: "{{ target_object.ip.split('.')[3] }}"
        first_digit: "{{ target_object.ip.split('.')[3][0] }}"
        last_two_digits: "{{ target_object.ip.split('.')[3][1:] }}"
        reserved_mac: "ff:ff:ff:ff:f{{ target_object.ip.split('.')[3][0] }}:{{ target_object.ip.split('.')[3][1:] }}"
      when: target_object is defined

    # 顯示計算過程（分步顯示）
    - name: "🧮 MAC Calculation Process"
      ansible.builtin.debug:
        msg: "🧮 MAC計算 | IP: {{ target_object.ip }} | 第四碼: {{ ip_fourth_octet }} | 第一位: {{ first_digit }} | 後兩位: {{ last_two_digits }}"

    - name: "🧮 MAC Calculation Result"
      ansible.builtin.debug:
        msg: "🔧 MAC格式: ff:ff:ff:ff:f{{ first_digit }}:{{ last_two_digits }} | 結果: {{ reserved_mac }}"

    # 顯示預覽結果（分段顯示）
    - name: "✅ Target Configuration Found"
      ansible.builtin.debug:
        msg: "✅ 找到目標MAC配置 ========================================="

    - name: "📊 Current Configuration"
      ansible.builtin.debug:
        msg: "📊 當前 | ID: {{ target_object.id }} | IP: {{ target_object.ip }} | MAC: {{ target_object.mac }} | 描述: {{ target_object.description | default('空白') }}"

    - name: "🔄 After Delete Configuration" 
      ansible.builtin.debug:
        msg: "🔄 還原 | ID: {{ target_object.id }} | IP: {{ target_object.ip }} | MAC: {{ reserved_mac }} | 描述: Reserved"

    - name: "📐 MAC Restore Rule"
      ansible.builtin.debug:
        msg: "📐 規則 | IP第四碼 {{ ip_fourth_octet }} → MAC ff:ff:ff:ff:f{{ first_digit }}:{{ last_two_digits }} | 描述統一為Reserved"

    - name: "⚠️ Configuration Change Warning"
      ansible.builtin.debug:
        msg: "⚠️ 警告：此操作將永久修改FortiGate配置！請在Approval Node中仔細確認後再批准執行。"

    # 設定workflow變數
    - name: "📤 Set Workflow Variables"
      ansible.builtin.set_stats:
        data:
          wf_target_id: "{{ target_object.id }}"
          wf_target_ip: "{{ target_object.ip }}"
          wf_original_mac: "{{ target_object.mac }}"
          wf_reserved_mac: "{{ reserved_mac }}"
          wf_original_desc: "{{ target_object.description | default('') }}"
          wf_server_id: "{{ dhcp_server_id }}"
          wf_delete_mac: "{{ delete_mac }}"
          wf_ip_fourth_octet: "{{ ip_fourth_octet }}"
          wf_first_digit: "{{ first_digit }}"
          wf_last_two_digits: "{{ last_two_digits }}"

    - name: "🎯 Preview Complete"
      ansible.builtin.debug:
        msg: "🎯 預覽完成 | 等待人工確認 | MAC {{ delete_mac }} → {{ reserved_mac }} | IP {{ target_object.ip }}"
