---
- name: Test Pause Without Wait
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: "🧪 測試pause的不同參數"
      ansible.builtin.debug:
        msg: "開始測試pause參數"

    # 測試2: seconds設為0
    - name: "🔍 測試B: pause seconds=0"
      ansible.builtin.pause:
        seconds: 0
        prompt: |
          📊 測試B: seconds=0
          
          基本參數:
          - IP: 172.23.40.172
          - MAC: aa:bb:cc:dd:ee:ff

    # 測試3: 只用prompt，無seconds
    - name: "🔍 測試C: 只用prompt"
      ansible.builtin.pause:
        prompt: |
          📊 測試C: 只用prompt無seconds
          
          基本參數:
          - IP: 172.23.40.172
          - MAC: aa:bb:cc:dd:ee:ff
