---
- name: Create or Update FortiGate Firewall Address
  # 永遠在 AWX 執行節點上運行
  hosts: localhost
  
  # 使用 httpapi 連線到遠端的 FortiGate
  connection: httpapi
  
  collections:
    - fortinet.fortios
  
  gather_facts: false

  # --- 正確的變數定義 ---
  vars:
    # 關鍵修正: 告訴 httpapi 外掛程式要去連線的目標主機
    ansible_host: "{{ lookup('env', 'FORTIGATE_HOST') }}"
    
    # httpapi 外掛程式需要的其他連線變數
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_access_token: "{{ lookup('env', 'FORTIGATE_API_TOKEN') }}"

  tasks:
    - name: Ensure firewall address object exists
      fortinet.fortios.fortios_firewall_address:
        # 任務本身保持乾淨，所有連線細節都在上面的 vars 區塊處理
        state: "present"
        firewall_address:
          name: "{{ address_name | default('AWX_Final_Correct_Address') }}"
          subnet: "{{ address_subnet | default('3.3.3.3/32') }}"
          type: "ipmask"
          comment: "Managed by Ansible AWX - The Right Way"
