---
- name: Create FortiGate Address Object (Official Example)
  hosts: all
  connection: httpapi
  collections:
    - fortinet.fortios
  gather_facts: false

  tasks:
    - name: Create new firewall address for 'webserver1'
      fortios_firewall_address:
        # vdom 參數非常重要，即使是預設的 root 也請加上
        vdom: "root"
        
        # state: "present" 確保這個物件存在
        state: "present"
        
        # address 字典定義了物件的屬性
        address:
          name: "webserver1-official-example"
          subnet: "192.168.1.100/32"
          comment: "Created via official AWX example"
