---
- name: Create or Update FortiGate Firewall Address
  hosts: localhost
  connection: local
  gather_facts: false

  # --- 關鍵修正 ---
  # 在這裡設定環境變數，將您 Credential Injector 的變數
  # 映射成 FortiOS Collection 預期讀取的變數名稱。
  environment:
    FORTIOS_HOST: "{{ lookup('env', 'FORTIGATE_HOST') }}"

  tasks:
    - name: Ensure firewall address object exists
      fortinet.fortios.fortios_firewall_address:
        # access_token 是模組支援的參數，可以直接傳遞
        access_token: "{{ lookup('env', 'FORTIGATE_API_TOKEN') }}"
        
        # vdom: "root" # 如果您有多個 VDOM，請取消註解並指定

        # 這裡不再需要 host 和 validate_certs 參數
        
        state: "present"
        firewall_address:
          name: "{{ address_name | default('AWX_Default_Test_Address') }}"
          subnet: "{{ address_subnet | default('1.1.1.1/32') }}"
          type: "ipmask"
          comment: "Managed by Ansible AWX"
