---
- name: Create FortiGate Firewall Address Object
  hosts: all
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
  vdom: "root"
  ansible_httpapi_use_ssl: true
  ansible_httpapi_validate_certs: false
  ansible_httpapi_port: 443
  gather_facts: false

  tasks:
    - name: Create a new firewall address object for a test server
      fortinet.fortios.fortios_firewall_address:
      state: “present”
      firewall_address:
      name: test_123
      subnet: 10.1.1.1 255.255.255.0
