---
- name: Create FortiGate Firewall Address
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a firewall address
      uri:
        url: "{{ lookup('env', 'FORTIGATE_HOST') }}/api/v2/cmdb/firewall/address"
        method: POST
        headers:
          Authorization: "Bearer {{ lookup('env', 'FORTIGATE_API_TOKEN') }}"
          Content-Type: "application/json"
        body: 
          name: "my_test_address"
          subnet: "10.10.10.0 255.255.255.0"
          type: "subnet"
        body_format: json
        validate_certs: false
      register: result

    - debug:
        var: result.json
