---
- name: Create FortiGate Firewall Address Object
  hosts: all
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
  vdom: "root"
  ansible_httpapi_use_ssl: true
  ansible_httpapi_validate_certs: false
  ansible_httpapi_port: 443
  gather_facts: false

  tasks:
    - name: Create a new firewall address object for a test server
      fortios_firewall_address:
        state: "present"
        address:
          name: "Test-Server-01"
          subnet: "192.168.100.101/32"
          comment: "Managed by Ansible AWX"
