---
- name: Extract FortiGate Security Rating Unused Policies Data
  hosts: localhost
  gather_facts: false
  vars:
    fortigate_api_url: "https://{{ fortigate_host }}:{{ fortigate_api_port | default('443') }}"

  tasks:
    - name: 🎯 測試發現的 Security Rating API
      uri:
        url: "{{ fortigate_api_url }}/api/v2/monitor/system/security-rating"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          report_type: "TopologyReport"
          id: "{{ security_rating_id | default('1757052908321') }}"
          vdom: "{{ vdom_name | default('root') }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: 30
      register: security_rating_data

    - name: 📋 顯示 Security Rating 回應結構
      debug:
        msg: |
          🎯 Security Rating API 結果:
          ✅ Status: {{ security_rating_data.status }}
          📊 Response Keys: {{ security_rating_data.json.keys()|list if security_rating_data.json is defined else 'No JSON' }}
          
          {% if security_rating_data.json.results is defined %}
          📈 Results Count: {{ security_rating_data.json.results|length }}
          {% endif %}
      when: security_rating_data.status == 200

    - name: 🔍 分析 Security Rating 資料結構
      debug:
        msg: |
          ========= 🔍 Security Rating 資料分析 =========
          
          {% if security_rating_data.json.results is defined %}
          📊 找到 {{ security_rating_data.json.results|length }} 筆結果
          
          {% for result in security_rating_data.json.results %}
          
          📋 結果 {{ loop.index }}:
          - Keys: {{ result.keys()|list }}
          {% if result.recommendations is defined %}
          - 推薦項目數: {{ result.recommendations|length }}
          {% endif %}
          {% if result.unused_policies is defined %}
          🎯 找到 Unused Policies！
          {% endif %}
          
          {% endfor %}
          {% else %}
          📋 完整回應內容:
          {{ security_rating_data.json | to_nice_json }}
          {% endif %}
          =============================================
      when: security_rating_data.status == 200

    # 嘗試不同的 report_type
    - name: 🔍 測試不同的 Report Type
      uri:
        url: "{{ fortigate_api_url }}/api/v2/monitor/system/security-rating"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          report_type: "{{ item }}"
          id: "{{ security_rating_id | default('1757052908321') }}"
          vdom: "{{ vdom_name | default('root') }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: 30
        status_code: [200, 400, 404]
      register: report_type_tests
      loop:
        - "SecurityReport"
        - "PolicyReport"
        - "UnusedPolicyReport"
        - "ComplianceReport"
        - "RecommendationReport"
      failed_when: false

    - name: 📊 顯示不同 Report Type 結果
      debug:
        msg: |
          🎯 {{ item.item }}: {{ '✅' if item.status == 200 else '❌' }} ({{ item.status }})
          {% if item.status == 200 and item.json.results is defined %}
          📈 Results: {{ item.json.results|length }}
          {% endif %}
      loop: "{{ report_type_tests.results }}"

    # 嘗試不使用 ID 參數
    - name: 🔍 測試不帶 ID 的請求
      uri:
        url: "{{ fortigate_api_url }}/api/v2/monitor/system/security-rating"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          report_type: "TopologyReport"
          vdom: "{{ vdom_name | default('root') }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: 30
        status_code: [200, 400, 404]
      register: no_id_test
      failed_when: false

    - name: 📋 顯示不帶ID的結果
      debug:
        msg: |
          🎯 不帶ID的請求: {{ '✅' if no_id_test.status == 200 else '❌' }} ({{ no_id_test.status }})
          {% if no_id_test.status == 200 %}
          📊 與帶ID結果相同: {{ '是' if no_id_test.json == security_rating_data.json else '否' }}
          {% endif %}

    # 提取 Unused Policies 資料
    - name: 🎯 提取 Unused Policies 資料
      debug:
        msg: |
          ========= 🎯 Unused Policies 資料 =========
          
          {% set found_unused = false %}
          {% for test_result in [security_rating_data] + report_type_tests.results + [no_id_test] %}
          {% if test_result.status == 200 and test_result.json is defined %}
          
          {% if test_result.json.results is defined %}
          {% for result in test_result.json.results %}
          {% if result.recommendations is defined %}
          {% for rec in result.recommendations %}
          {% if 'unused' in rec|string|lower or 'policy' in rec|string|lower %}
          {% set found_unused = true %}
          
          🎯 找到 Unused Policy 推薦:
          {{ rec | to_nice_json }}
          
          {% endif %}
          {% endfor %}
          {% endif %}
          {% endfor %}
          {% endif %}
          
          {% endif %}
          {% endfor %}
          
          {% if not found_unused %}
          ⚠️ 在API回應中未找到明確的 unused policies 資料
          💡 可能需要：
          1. 確認 ID 參數是否正確
          2. 檢查是否需要先觸發分析
          3. 嘗試其他 report_type
          {% endif %}
          ==========================================

    # 生成當前時間戳作為新的ID嘗試
    - name: 🕐 生成新的時間戳ID測試
      set_fact:
        current_timestamp: "{{ ansible_date_time.epoch }}000"  # 轉換為毫秒

    - name: 🔍 使用新時間戳測試
      uri:
        url: "{{ fortigate_api_url }}/api/v2/monitor/system/security-rating"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          report_type: "TopologyReport"
          id: "{{ current_timestamp }}"
          vdom: "{{ vdom_name | default('root') }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: 30
        status_code: [200, 400, 404]
      register: new_timestamp_test
      failed_when: false

    - name: 📊 總結所有測試結果
      debug:
        msg: |
          ========= 🎯 Security Rating API 測試總結 =========
          
          ✅ 原始ID成功: {{ '是' if security_rating_data.status == 200 else '否' }}
          ✅ 不同report_type成功: {{ report_type_tests.results | selectattr('status', 'equalto', 200) | list | length }}/{{ report_type_tests.results | length }}
          ✅ 不帶ID成功: {{ '是' if no_id_test.status == 200 else '否' }}  
          ✅ 新時間戳成功: {{ '是' if new_timestamp_test.status == 200 else '否' }}
          
          🎯 下一步建議:
          {% if security_rating_data.status == 200 %}
          1. ✅ API端點有效，檢查回應中的 unused policies 資料
          2. 🔍 分析 recommendations 或 results 結構
          3. 📋 確認資料格式並提取所需欄位
          {% else %}
          1. ⚠️ 檢查ID參數是否過期
          2. 🔄 在GUI中重新執行Security Rating分析
          3. 📱 重新抓取新的API請求
          {% endif %}
          ===============================================
