---
- name: Extract FortiGate Security Rating Unused Policies (Fixed Slice)
  hosts: localhost
  gather_facts: false
  vars:
    fortigate_api_url: "https://{{ fortigate_host }}:{{ fortigate_api_port | default('443') }}"

  tasks:
    - name: 🎯 取得 Security Rating 資料
      uri:
        url: "{{ fortigate_api_url }}/api/v2/monitor/system/security-rating"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          report_type: "TopologyReport"
          id: "{{ security_rating_id | default('1757052908321') }}"
          vdom: "{{ vdom_name | default('root') }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: 30
      register: security_rating_data

    - name: 📋 顯示基本資訊
      debug:
        msg: |
          ✅ Status: {{ security_rating_data.status }}
          📊 Response Keys: {{ security_rating_data.json.keys()|list }}
          📈 Results Count: {{ security_rating_data.json.results|length if security_rating_data.json.results is defined else 0 }}
          🏢 Devices Count: {{ security_rating_data.json.devices|length if security_rating_data.json.devices is defined else 0 }}

    - name: 🔍 分析 Results 結構
      debug:
        msg: |
          ========= 📊 Results 分析 =========
          {% if security_rating_data.json.results is defined %}
          {% for result in security_rating_data.json.results %}
          {% if loop.index <= 3 %}
          
          📋 Result {{ loop.index }}:
          {% if result is mapping %}
          - Type: Dictionary
          - Keys: {{ result.keys()|list }}
          {% if result.name is defined %}
          - Name: {{ result.name }}
          {% endif %}
          {% if result.category is defined %}
          - Category: {{ result.category }}
          {% endif %}
          {% if result.checkName is defined %}
          - Check Name: {{ result.checkName }}
          {% endif %}
          {% else %}
          - Type: String/Other
          - Value: {{ result }}
          {% endif %}
          
          {% endif %}
          {% endfor %}
          {% if security_rating_data.json.results|length > 3 %}
          ... (showing 3 of {{ security_rating_data.json.results|length }})
          {% endif %}
          {% endif %}
          =================================

    - name: 🏢 分析 Devices 資料
      debug:
        msg: |
          ========= 🏢 Devices 分析 =========
          {% if security_rating_data.json.devices is defined %}
          
          📊 設備總數: {{ security_rating_data.json.devices|length }}
          
          {% for device in security_rating_data.json.devices %}
          {% if loop.index <= 2 %}
          
          📱 Device {{ loop.index }}:
          {% if device is mapping %}
          - Keys: {{ device.keys()|list }}
          {% if device.deviceName is defined %}
          - Name: {{ device.deviceName }}
          {% endif %}
          {% if device.serialNumber is defined %}
          - Serial: {{ device.serialNumber }}
          {% endif %}
          {% endif %}
          
          {% endif %}
          {% endfor %}
          {% endif %}
          ===============================

    # 專門尋找 unused policy 相關資料
    - name: 🎯 搜尋所有欄位中的 Unused Policy 資訊
      debug:
        msg: |
          ========= 🔍 深度搜尋 Unused Policies =========
          
          {% set found_policies = [] %}
          
          🔍 搜尋 Results 中的 Policy 資訊:
          {% if security_rating_data.json.results is defined %}
          {% for result in security_rating_data.json.results %}
          {% if result is mapping %}
          {% if 'unused' in result|string|lower or 'policy' in result|string|lower %}
          
          🎯 在 Results 中找到可能的 Policy 資訊:
          {% if result.checkName is defined %}
          - Check Name: {{ result.checkName }}
          {% endif %}
          {% if result.category is defined %}
          - Category: {{ result.category }}
          {% endif %}
          {% if result.deviceResults is defined %}
          - Device Results: {{ result.deviceResults|length }} 個設備
          
          {% for deviceResult in result.deviceResults %}
          {% if deviceResult.details is defined %}
          🎯 Device Details 找到！
          {% if deviceResult.details.policies is defined %}
          📋 Policies: {{ deviceResult.details.policies|length }} 個
          {% for policy in deviceResult.details.policies %}
          {% if loop.index <= 5 %}
          - Policy {{ policy.id if policy.id is defined else 'N/A' }}: Last Used {{ policy.lastUsed if policy.lastUsed is defined else 'Never' }}
          {% endif %}
          {% endfor %}
          {% endif %}
          {% endif %}
          {% endfor %}
          
          {% endif %}
          {% endif %}
          {% endif %}
          {% endfor %}
          {% endif %}
          
          🔍 搜尋 Devices 中的 Policy 資訊:
          {% if security_rating_data.json.devices is defined %}
          {% for device in security_rating_data.json.devices %}
          {% if device is mapping and device.deviceResults is defined %}
          {% for deviceResult in device.deviceResults %}
          {% if deviceResult is mapping and 'unused' in deviceResult|string|lower %}
          
          🎯 在 Device Results 中找到 Unused 資訊:
          Device: {{ device.deviceName if device.deviceName is defined else 'Unknown' }}
          
          {% endif %}
          {% endfor %}
          {% endif %}
          {% endfor %}
          {% endif %}
          ==========================================

    # 如果上面沒找到，顯示更詳細的結構
    - name: 📝 如果沒找到，顯示詳細結構
      debug:
        msg: |
          ========= 📝 詳細結構分析 =========
          
          {% if security_rating_data.json.results is defined %}
          🔍 第一個 Result 的完整結構:
          {% for result in security_rating_data.json.results %}
          {% if loop.index == 1 and result is mapping %}
          {{ result | to_nice_json }}
          {% endif %}
          {% if loop.index == 1 %}
          {% break %}
          {% endif %}
          {% endfor %}
          {% endif %}
          
          {% if security_rating_data.json.devices is defined %}
          🔍 第一個 Device 的完整結構:
          {% for device in security_rating_data.json.devices %}
          {% if loop.index == 1 and device is mapping %}
          {{ device | to_nice_json }}
          {% endif %}
          {% if loop.index == 1 %}
          {% break %}
          {% endif %}
          {% endfor %}
          {% endif %}
          ===================================

    - name: 💡 下一步建議
      debug:
        msg: |
          💡 根據API回應分析:
          
          ✅ API 成功取得資料
          📊 共有 {{ security_rating_data.json.results|length if security_rating_data.json.results is defined else 0 }} 個檢查結果
          🏢 共有 {{ security_rating_data.json.devices|length if security_rating_data.json.devices is defined else 0 }} 個設備
          
          🔍 尋找策略:
          1. 檢查 results[] 中是否有 checkName 包含 "Unused Policies"
          2. 分析 deviceResults[].details.policies 結構
          3. 尋找包含 policy ID 和 lastUsed 時間的資料
          
          📋 如果仍未找到，可能需要:
          - 確認GUI中的分析已完成
          - 嘗試不同的 report_type 參數
          - 檢查是否需要特定的權限或授權
