---
- name: FortiGate Unused Policies Extractor (Fixed)
  hosts: localhost
  gather_facts: false
  vars:
    fortigate_api_url: "https://{{ fortigate_host }}:{{ fortigate_api_port | default('443') }}"
    
  tasks:
    - name: 🎯 獲取所有 Policy 資料
      uri:
        url: "{{ fortigate_api_url }}/api/v2/monitor/firewall/policy"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          vdom: "{{ vdom_name | default('root') }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: 30
      register: all_policies

    - name: 🔍 篩選 Unused Policies
      set_fact:
        unused_policies: "{{ all_policies.json.results | selectattr('bytes', 'equalto', 0) | selectattr('packets', 'equalto', 0) | list }}"

    - name: 📊 Policy 統計總覽
      debug:
        msg: |
          ========= 📊 Policy 統計總覽 =========
          🏢 VDOM: {{ vdom_name | default('root') }}
          📋 總 Policies: {{ all_policies.json.results | length }}
          🎯 Unused Policies: {{ unused_policies | length }}
          📊 Used Policies: {{ (all_policies.json.results | length) - (unused_policies | length) }}
          
          📈 Unused 比例: {{ ((unused_policies | length / all_policies.json.results | length) * 100) | round(1) }}%
          ====================================

    - name: 🎯 顯示 Unused Policies 清單
      debug:
        msg: |
          ========= 🎯 Unused Policies 詳細清單 =========
          
          {% if unused_policies | length > 0 %}
          {% for policy in unused_policies | sort(attribute='policyid') %}
          
          📋 Policy {{ policy.policyid }}:
          - Bytes: {{ policy.bytes }}
          - Packets: {{ policy.packets }}  
          - Hit Count: {{ policy.hit_count }}
          - Session Count: {{ policy.session_count }}
          - Last Used: {{ 'Never' if policy.last_used == 0 else (policy.last_used | int | strftime('%Y-%m-%d %H:%M:%S')) }}
          - First Used: {{ 'Never' if policy.first_used == 0 else (policy.first_used | int | strftime('%Y-%m-%d %H:%M:%S')) }}
          
          {% endfor %}
          {% else %}
          ✅ 所有 policies 都有使用記錄！
          {% endif %}
          ===============================================

    - name: 📋 Unused Policies 摘要
      debug:
        msg: |
          ========= 📋 Unused Policies 摘要 =========
          
          {% if unused_policies | length > 0 %}
          {% set never_used = unused_policies | selectattr('last_used', 'equalto', 0) | list %}
          {% set old_unused = unused_policies | rejectattr('last_used', 'equalto', 0) | list %}
          
          📊 分類統計:
          - Never Used: {{ never_used | length }} policies
          - Previously Used (但現在未使用): {{ old_unused | length }} policies
          
          📋 Never Used Policy IDs: 
          {{ never_used | map(attribute='policyid') | list | sort | join(', ') }}
          
          📋 All Unused Policy IDs:
          {{ unused_policies | map(attribute='policyid') | list | sort | join(', ') }}
          
          {% else %}
          ✅ 沒有發現 unused policies
          {% endif %}
          =========================================

    # 生成 CSV 格式輸出 (更實用)
    - name: 📄 生成 CSV 格式輸出
      debug:
        msg: |
          ========= 📄 CSV 格式輸出 =========
          
          Policy ID,Bytes,Packets,Hit Count,Session Count,Last Used,First Used,Status
          {% for policy in unused_policies | sort(attribute='policyid') %}
          {{ policy.policyid }},{{ policy.bytes }},{{ policy.packets }},{{ policy.hit_count }},{{ policy.session_count }},"{{ 'Never' if policy.last_used == 0 else (policy.last_used | int | strftime('%Y-%m-%d %H:%M:%S')) }}","{{ 'Never' if policy.first_used == 0 else (policy.first_used | int | strftime('%Y-%m-%d %H:%M:%S')) }}","{{ 'Never Used' if policy.last_used == 0 else 'Previously Used' }}"
          {% endfor %}
          
          ===================================

    # 生成簡潔的 JSON 輸出
    - name: 📤 生成 JSON 格式輸出
      debug:
        msg: |
          ========= 📤 JSON 格式輸出 =========
          
          {
            "scan_info": {
              "vdom": "{{ vdom_name | default('root') }}",
              "scan_time": "{{ ansible_date_time.iso8601 }}",
              "fortigate_host": "{{ fortigate_host }}"
            },
            "summary": {
              "total_policies": {{ all_policies.json.results | length }},
              "unused_policies": {{ unused_policies | length }},
              "used_policies": {{ (all_policies.json.results | length) - (unused_policies | length) }},
              "unused_percentage": {{ ((unused_policies | length / all_policies.json.results | length) * 100) | round(1) }}
            },
            "unused_policy_ids": {{ unused_policies | map(attribute='policyid') | list | sort }},
            "unused_policies_detail": [
              {% for policy in unused_policies | sort(attribute='policyid') %}
              {
                "policyid": {{ policy.policyid }},
                "bytes": {{ policy.bytes }},
                "packets": {{ policy.packets }},
                "hit_count": {{ policy.hit_count }},
                "session_count": {{ policy.session_count }},
                "last_used_timestamp": {{ policy.last_used }},
                "last_used_readable": "{{ 'Never' if policy.last_used == 0 else (policy.last_used | int | strftime('%Y-%m-%d %H:%M:%S')) }}",
                "first_used_timestamp": {{ policy.first_used }},
                "status": "{{ 'Never Used' if policy.last_used == 0 else 'Previously Used' }}"
              }{{ ',' if not loop.last else '' }}
              {% endfor %}
            ]
          }
          ===================================

    # 建議的後續動作
    - name: 💡 建議的後續動作
      debug:
        msg: |
          ========= 💡 建議的後續動作 =========
          
          {% if unused_policies | length > 0 %}
          🔍 發現 {{ unused_policies | length }} 個 unused policies，建議：
          
          1️⃣ 檢查 Policy 用途:
          - 使用 GUI 檢視這些 policies 的配置
          - 確認是否為測試或備用 policies
          
          2️⃣ 安全移除步驟:
          - 將 policies 設為 disable 而非直接刪除  
          - 觀察一段時間確認沒有影響
          - 再考慮完全移除
          
          3️⃣ 定期監控:
          - 建議每月執行此 playbook 檢查
          - 追蹤 unused policies 的變化
          
          {% set never_used_count = unused_policies | selectattr('last_used', 'equalto', 0) | list | length %}
          📊 優先處理建議:
          - 優先檢查 {{ never_used_count }} 個從未使用的 policies
          - 謹慎處理曾經使用過的 policies
          
          {% else %}
          ✅ 恭喜！所有 policies 都在使用中
          💡 建議定期執行此檢查以維持 policy 清潔度
          {% endif %}
          =====================================

    - name: 🎯 執行完成
      debug:
        msg: |
          ========= 🎯 任務執行完成 =========
          
          ✅ 成功分析 FortiGate unused policies
          📊 總共檢查了 {{ all_policies.json.results | length }} 條 policies
          🎯 識別出 {{ unused_policies | length }} 個 unused policies
          
          📋 Unused Policy IDs: {{ unused_policies | map(attribute='policyid') | list | sort | join(', ') if unused_policies | length > 0 else '無' }}
          
          💾 輸出格式已提供:
          - 詳細清單
          - CSV 格式 (可匯入 Excel)
          - JSON 格式 (程式處理)
          
          🚀 Playbook 可以定期執行進行監控！
          =================================
