---
- name: Collect FortiGate Security Rating Unused Policies
  hosts: localhost
  gather_facts: false
  vars:
    fortigate_api_url: "https://{{ fortigate_host }}:{{ fortigate_api_port | default('443') }}"

  tasks:
    - name: 收集 Security Rating 資訊
      debug:
        msg: "🔍 嘗試收集 Security Rating Unused Policies 資料"

    # 嘗試最有可能的幾個端點
    - name: 測試 Security Rating 端點
      uri:
        url: "{{ fortigate_api_url }}{{ item }}"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          vdom: "{{ vdom_name | default('root') }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: 30
        status_code: [200, 400, 404]
      register: endpoint_tests
      loop:
        - "/api/v2/monitor/system/security-rating"
        - "/api/v2/monitor/system/security-rating/results" 
        - "/api/v2/monitor/system/csf/security-rating"
        - "/api/v2/monitor/system/csf"
      failed_when: false

    # 顯示簡潔結果
    - name: 顯示端點測試結果
      debug:
        msg: |
          {{ item.item }}: {{ '✅' if item.status == 200 else '❌' }} ({{ item.status }})
          {% if item.status == 200 and item.json.results is defined %}
          - 有results資料: {{ item.json.results | length }} 筆
          {% elif item.status == 200 %}
          - 回應欄位: {{ item.json.keys() | list }}
          {% endif %}
      loop: "{{ endpoint_tests.results }}"

    # 嘗試CSF相關的unused policies查詢
    - name: 測試 CSF Unused Policies 查詢
      uri:
        url: "{{ fortigate_api_url }}/api/v2/monitor/system/csf"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          vdom: "{{ vdom_name | default('root') }}"
          action: "{{ item }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: 30
        status_code: [200, 400, 404]
      register: csf_action_tests
      loop:
        - "get-security-rating"
        - "get-unused-policies" 
        - "security-rating"
        - "unused-policy"
      failed_when: false

    - name: 顯示 CSF 查詢結果
      debug:
        msg: |
          CSF Action "{{ item.item }}": {{ '✅' if item.status == 200 else '❌' }} ({{ item.status }})
          {% if item.status == 200 and item.json != endpoint_tests.results[0].json %}
          🎯 發現不同的回應!
          {% endif %}
      loop: "{{ csf_action_tests.results }}"

    # 嘗試POST方法觸發或取得結果
    - name: 嘗試取得 Security Rating 結果
      uri:
        url: "{{ fortigate_api_url }}/api/v2/monitor/system/security-rating"
        method: POST
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          vdom: "{{ vdom_name | default('root') }}"
          action: "get-results"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: 30
        status_code: [200, 400, 404, 405]
      register: post_test
      failed_when: false

    - name: 顯示 POST 測試結果
      debug:
        msg: |
          POST Security Rating: {{ '✅' if post_test.status == 200 else '❌' }} ({{ post_test.status }})
          {% if post_test.status == 200 %}
          🎯 POST 成功! 可能找到了正確方法
          {% endif %}

    # 顯示任何有實際資料的回應
    - name: 顯示有資料的回應內容
      debug:
        msg: |
          ========= 發現資料: {{ item.url | default(item.item) }} =========
          {{ item.json | to_nice_json }}
          =============================================
      loop: "{{ endpoint_tests.results + csf_action_tests.results + [post_test] }}"
      when: 
        - item.status == 200
        - item.json is defined
        - item.json | length > 5
        - "'STATIC' not in (item.json | string)"

    # 總結發現
    - name: 總結收集結果
      debug:
        msg: |
          🎯 Security Rating 資訊收集完成
          
          📊 測試結果:
          - GET 端點成功: {{ endpoint_tests.results | selectattr('status', 'equalto', 200) | list | length }}/{{ endpoint_tests.results | length }}
          - CSF Action成功: {{ csf_action_tests.results | selectattr('status', 'equalto', 200) | list | length }}/{{ csf_action_tests.results | length }}
          - POST 測試: {{ '成功' if post_test.status == 200 else '失敗' }}
          
          💡 下一步:
          {% set has_data = false %}
          {% for item in endpoint_tests.results + csf_action_tests.results + [post_test] %}
          {% if item.status == 200 and item.json is defined and item.json | length > 5 and 'STATIC' not in (item.json | string) %}
          {% set has_data = true %}
          {% endif %}
          {% endfor %}
          {% if has_data %}
          - ✅ 找到有實際資料的端點，可以進一步分析
          {% else %}
          - ⚠️ 尚未找到unused policies資料，可能需要：
            1. 在GUI中先執行Security Rating分析  
            2. 檢查是否有相關授權
            3. 嘗試其他API路徑
          {% endif %}
