---
- name: Find FortiGate Unused Policies in Security Rating Data
  hosts: localhost
  gather_facts: false
  vars:
    fortigate_api_url: "https://{{ fortigate_host }}:{{ fortigate_api_port | default('443') }}"

  tasks:
    - name: 🎯 取得 Security Rating 資料
      uri:
        url: "{{ fortigate_api_url }}/api/v2/monitor/system/security-rating"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          report_type: "TopologyReport"
          id: "{{ security_rating_id | default('1757052908321') }}"
          vdom: "{{ vdom_name | default('root') }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: 30
      register: security_rating_data

    - name: 📊 分析關鍵欄位的資料類型和大小
      debug:
        msg: |
          ========= 📊 關鍵欄位分析 =========
          {% for key, value in security_rating_data.json.items() %}
          {% if key in ['devices', 'perDeviceStatistics', 'perCheckStatistics', 'perCategoryStatistics', 'weekHistory', 'statistics'] %}
          
          🔍 {{ key }}:
          - Type: {{ value|type_debug }}
          - Size: {{ value|length if value is iterable and value is not string else 'N/A' }}
          {% if value is iterable and value is not string and value|length > 0 %}
          {% set first_item = value[0] if value is sequence else value.values()|list|first %}
          - First Item Type: {{ first_item|type_debug }}
          {% if first_item is mapping %}
          - First Item Keys: {{ first_item.keys()|list }}
          {% endif %}
          {% endif %}
          
          {% endif %}
          {% endfor %}
          ===================================

    - name: 🏢 詳細分析第一個 Device
      debug:
        msg: |
          ========= 🏢 第一個設備詳細資料 =========
          {% if security_rating_data.json.devices is defined and security_rating_data.json.devices|length > 0 %}
          {% set first_device = security_rating_data.json.devices[0] %}
          
          📱 設備資訊:
          {% for key, value in first_device.items() %}
          - {{ key }}: {{ value }}
          {% endfor %}
          
          {% else %}
          ⚠️ 沒有設備資料
          {% endif %}
          ======================================

    - name: 📈 分析 perDeviceStatistics (可能包含 Policy 統計)
      debug:
        msg: |
          ========= 📈 perDeviceStatistics 分析 =========
          {% if security_rating_data.json.perDeviceStatistics is defined %}
          
          📊 統計資料類型: {{ security_rating_data.json.perDeviceStatistics|type_debug }}
          📊 統計資料大小: {{ security_rating_data.json.perDeviceStatistics|length if security_rating_data.json.perDeviceStatistics is iterable and security_rating_data.json.perDeviceStatistics is not string else 'N/A' }}
          
          {% if security_rating_data.json.perDeviceStatistics is mapping %}
          🔍 統計欄位:
          {% for key, value in security_rating_data.json.perDeviceStatistics.items() %}
          - {{ key }}: {{ value|type_debug }} ({{ value|length if value is iterable and value is not string else value }})
          {% endfor %}
          {% endif %}
          
          {% endif %}
          ============================================

    - name: 🔍 檢查 perCheckStatistics (檢查統計)
      debug:
        msg: |
          ========= 🔍 perCheckStatistics 分析 =========
          {% if security_rating_data.json.perCheckStatistics is defined %}
          
          📊 檢查統計類型: {{ security_rating_data.json.perCheckStatistics|type_debug }}
          
          {% if security_rating_data.json.perCheckStatistics is mapping %}
          🎯 尋找 Unused Policy 相關檢查:
          {% for check_name, check_data in security_rating_data.json.perCheckStatistics.items() %}
          {% if 'unused' in check_name|lower or 'policy' in check_name|lower %}
          
          🎯 找到相關檢查: {{ check_name }}
          - 資料: {{ check_data }}
          
          {% endif %}
          {% endfor %}
          
          📋 所有檢查項目:
          {% for check_name in security_rating_data.json.perCheckStatistics.keys() %}
          - {{ check_name }}
          {% endfor %}
          {% endif %}
          
          {% endif %}
          ===========================================

    # 嘗試直接存取特定的 unused policy 檢查結果
    - name: 🎯 嘗試取得 Unused Policy 具體資料
      uri:
        url: "{{ fortigate_api_url }}/api/v2/monitor/system/security-rating"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          report_type: "TopologyReport"
          id: "{{ security_rating_id | default('1757052908321') }}"
          vdom: "{{ vdom_name | default('root') }}"
          checkName: "unused-policies"  # 嘗試特定檢查
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: 30
        status_code: [200, 400, 404]
      register: unused_policy_check
      failed_when: false

    - name: 📋 顯示 Unused Policy 檢查結果
      debug:
        msg: |
          🎯 Unused Policy 特定檢查: {{ '✅' if unused_policy_check.status == 200 else '❌' }} ({{ unused_policy_check.status }})
          {% if unused_policy_check.status == 200 %}
          📊 回應欄位: {{ unused_policy_check.json.keys()|list if unused_policy_check.json is defined else 'No JSON' }}
          {% endif %}

    # 嘗試使用 CSF API 的 unused-policy action
    - name: 🚀 嘗試 CSF unused-policy action
      uri:
        url: "{{ fortigate_api_url }}/api/v2/monitor/system/csf"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          vdom: "{{ vdom_name | default('root') }}"
          action: "unused-policy"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: 30
        status_code: [200, 400, 404]
      register: csf_unused_policy
      failed_when: false

    - name: 📊 顯示 CSF Unused Policy 結果
      debug:
        msg: |
          🎯 CSF unused-policy: {{ '✅' if csf_unused_policy.status == 200 else '❌' }} ({{ csf_unused_policy.status }})
          {% if csf_unused_policy.status == 200 and csf_unused_policy.json is defined %}
          
          📋 CSF 回應結構:
          {% for key, value in csf_unused_policy.json.items() %}
          - {{ key }}: {{ value|type_debug }} ({{ value|length if value is iterable and value is not string else value }})
          {% endfor %}
          
          {% if csf_unused_policy.json.results is defined %}
          🎯 CSF Results 內容:
          {{ csf_unused_policy.json.results | to_nice_json }}
          {% endif %}
          
          {% endif %}

    - name: 💡 總結和下一步建議
      debug:
        msg: |
          ========= 💡 分析總結 =========
          
          ✅ Security Rating API 成功
          📊 主要資料結構:
          - results: 字串陣列 (類別名稱)
          - devices: {{ security_rating_data.json.devices|length }} 個設備
          - perDeviceStatistics: 設備統計
          - perCheckStatistics: 檢查統計
          
          🔍 可能的 Policy 資料位置:
          1. perCheckStatistics 中的特定檢查項目
          2. CSF API 的 unused-policy action
          3. 需要其他 report_type 參數
          
          🎯 下一步建議:
          {% if csf_unused_policy.status == 200 %}
          ✅ CSF API 有回應，檢查是否包含 policy 資料
          {% else %}
          ⚠️ 可能需要在 GUI 中先執行完整的 Security Rating 分析
          {% endif %}
          =============================
