---
- name: Deep Analysis FortiGate Security Rating API
  hosts: localhost
  gather_facts: false
  vars:
    fortigate_api_url: "https://{{ fortigate_host }}:{{ fortigate_api_port | default('443') }}"

  tasks:
    - name: 🔍 深度分析成功的 CSF 端點
      uri:
        url: "{{ fortigate_api_url }}/api/v2/monitor/system/csf"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          vdom: "{{ vdom_name | default('root') }}"
          action: "{{ item }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: 30
      register: csf_detailed
      loop:
        - "get-security-rating"
        - "get-unused-policies" 
        - "security-rating"
        - "unused-policy"

    - name: 📊 分析 CSF 回應結構
      debug:
        msg: |
          ========= CSF Action: {{ item.item }} =========
          Status: {{ item.status }}
          Response Keys: {{ item.json.keys() | list if item.json is defined else 'No JSON' }}
          
          {% if item.json.results is defined %}
          📋 Results 結構:
          - Count: {{ item.json.results | length }}
          - Sample Keys: {{ item.json.results[0].keys() | list if item.json.results | length > 0 else 'Empty' }}
          {% endif %}
          
          {% if item.json.status is defined %}
          📋 Status: {{ item.json.status }}
          {% endif %}
          
          {% if item.json.message is defined %}
          📋 Message: {{ item.json.message }}
          {% endif %}
          
          🔍 完整回應: {{ item.json | to_nice_json }}
          ==========================================
      loop: "{{ csf_detailed.results }}"
      when: item.status == 200

    # 嘗試 Policy 相關的直接查詢
    - name: 🎯 測試直接 Policy 端點
      uri:
        url: "{{ fortigate_api_url }}{{ item }}"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          vdom: "{{ vdom_name | default('root') }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: 30
        status_code: [200, 400, 404]
      register: policy_tests
      loop:
        - "/api/v2/monitor/firewall/policy"
        - "/api/v2/monitor/firewall/policy/usage"
        - "/api/v2/monitor/system/policy-statistics"
        - "/api/v2/cmdb/firewall/policy"
      failed_when: false

    - name: 📈 顯示 Policy 端點結果
      debug:
        msg: |
          {{ item.item }}: {{ '✅' if item.status == 200 else '❌' }} ({{ item.status }})
          {% if item.status == 200 and item.json.results is defined %}
          - Results: {{ item.json.results | length }} policies
          {% elif item.status == 200 %}
          - Keys: {{ item.json.keys() | list }}
          {% endif %}
      loop: "{{ policy_tests.results }}"

    # 如果找到policy資料，分析usage資訊
    - name: 🔍 分析 Policy Usage 資料
      debug:
        msg: |
          ========= Policy Usage Analysis =========
          {% set policies_found = false %}
          {% for test in policy_tests.results %}
          {% if test.status == 200 and test.json.results is defined %}
          {% set policies_found = true %}
          📋 從 {{ test.item }} 找到 {{ test.json.results | length }} 條 policies
          
          {% for policy in test.json.results[:3] %}
          Policy {{ policy.policyid | default('N/A') }}:
          - Name: {{ policy.name | default('N/A') }}
          - Last Used: {{ policy.last_used | default('Never') }}
          - Bytes: {{ policy.bytes | default(0) }}
          - Packets: {{ policy.packets | default(0) }}
          {% endfor %}
          {% if test.json.results | length > 3 %}
          ... (showing first 3 of {{ test.json.results | length }})
          {% endif %}
          {% endif %}
          {% endfor %}
          
          {% if not policies_found %}
          ⚠️ 尚未在直接 policy 端點找到 usage 資料
          {% endif %}
          ==========================================
      when: policy_tests.results | selectattr('status', 'equalto', 200) | list | length > 0
