---
- name: FortiGate DHCP Delete Preview for Workflow
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    delete_mac: "{{ delete_mac_param }}"
    dhcp_server_id: "{{ server_id | default('3') }}"
    fortigate_host: "{{ fortigate_host }}"
    fortigate_token: "{{ fortigate_access_token }}"
    vdom_name: "{{ fortigate_vdom | default('root') }}"
    
  tasks:
    - name: "🔍 Get Current DHCP Reserved Addresses"
      ansible.builtin.uri:
        url: "https://{{ fortigate_host }}/api/v2/cmdb/system.dhcp/server/{{ dhcp_server_id }}/reserved-address"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_token }}"
        validate_certs: false
        status_code: 200
      register: existing_reservations

    - name: "🔍 Search for Target MAC"
      ansible.builtin.set_fact:
        target_object: "{{ item }}"
      loop: "{{ existing_reservations.json.results }}"
      when:
        - target_object is not defined
        - item.mac.lower() == delete_mac.lower()

    - name: "❌ MAC Not Found"
      ansible.builtin.fail:
        msg: "未找到MAC: {{ delete_mac }}"
      when: target_object is not defined

    - name: "🧮 Calculate Reserved MAC"
      ansible.builtin.set_fact:
        reserved_mac: "ff:ff:ff:ff:f1:{{ '%02d' | format(target_object.ip.split('.')[3] | int) }}"

    - name: "📋 Display Preview Information"
      ansible.builtin.debug:
        msg: |
          ✅ 找到要刪除的MAC配置：
          
          📊 當前配置：
          - ID: {{ target_object.id }}
          - IP: {{ target_object.ip }}
          - MAC: {{ target_object.mac }}
          - 描述: {{ target_object.description | default('無') }}
          
          🔄 刪除後將變為：
          - IP: {{ target_object.ip }} (不變)
          - MAC: {{ reserved_mac }}
          - 描述: Reserved

    # 重要：設定workflow變數供後續步驟使用
    - name: "📤 Set Workflow Variables"
      ansible.builtin.set_stats:
        data:
          wf_target_id: "{{ target_object.id }}"
          wf_target_ip: "{{ target_object.ip }}"  
          wf_original_mac: "{{ target_object.mac }}"
          wf_reserved_mac: "{{ reserved_mac }}"
          wf_original_desc: "{{ target_object.description | default('') }}"
          wf_server_id: "{{ dhcp_server_id }}"
          wf_delete_mac: "{{ delete_mac }}"
