---
- name: Extract FortiGate Security Rating Unused Policies Data (Fixed)
  hosts: localhost
  gather_facts: false
  vars:
    fortigate_api_url: "https://{{ fortigate_host }}:{{ fortigate_api_port | default('443') }}"

  tasks:
    - name: 🎯 取得 Security Rating 資料
      uri:
        url: "{{ fortigate_api_url }}/api/v2/monitor/system/security-rating"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          report_type: "TopologyReport"
          id: "{{ security_rating_id | default('1757052908321') }}"
          vdom: "{{ vdom_name | default('root') }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: 30
      register: security_rating_data

    - name: 📋 顯示基本資訊
      debug:
        msg: |
          ✅ Status: {{ security_rating_data.status }}
          📊 Response Keys: {{ security_rating_data.json.keys()|list }}
          📈 Results Count: {{ security_rating_data.json.results|length if security_rating_data.json.results is defined else 0 }}
          🏢 Devices Count: {{ security_rating_data.json.devices|length if security_rating_data.json.devices is defined else 0 }}
          🎯 Security Rating Results: {{ security_rating_data.json.securityRatingResults|length if security_rating_data.json.securityRatingResults is defined else 0 }}

    - name: 🔍 分析 Results 結構 (前3筆)
      debug:
        msg: |
          ========= 📊 Results 分析 =========
          {% if security_rating_data.json.results is defined %}
          {% for result in security_rating_data.json.results[:3] %}
          
          📋 Result {{ loop.index }}:
          {% if result is mapping %}
          - Type: Dictionary
          - Keys: {{ result.keys()|list }}
          {% if result.name is defined %}
          - Name: {{ result.name }}
          {% endif %}
          {% if result.category is defined %}
          - Category: {{ result.category }}
          {% endif %}
          {% if result.description is defined %}
          - Description: {{ result.description }}
          {% endif %}
          {% else %}
          - Type: {{ result|type_debug }}
          - Value: {{ result }}
          {% endif %}
          
          {% endfor %}
          {% if security_rating_data.json.results|length > 3 %}
          ... (showing 3 of {{ security_rating_data.json.results|length }})
          {% endif %}
          {% endif %}
          =================================

    - name: 🎯 分析 Security Rating Results
      debug:
        msg: |
          ========= 🎯 Security Rating Results =========
          {% if security_rating_data.json.securityRatingResults is defined %}
          {% for result in security_rating_data.json.securityRatingResults[:3] %}
          
          📊 Rating Result {{ loop.index }}:
          {% if result is mapping %}
          - Keys: {{ result.keys()|list }}
          {% if result.device is defined %}
          - Device: {{ result.device }}
          {% endif %}
          {% if result.recommendations is defined %}
          - Recommendations Count: {{ result.recommendations|length }}
          {% endif %}
          {% else %}
          - Value: {{ result }}
          {% endif %}
          
          {% endfor %}
          {% endif %}
          ========================================

    - name: 🔍 尋找 Unused Policies 相關資料
      debug:
        msg: |
          ========= 🔍 搜尋 Unused Policies =========
          
          {% set found_unused = [] %}
          
          {% if security_rating_data.json.results is defined %}
          {% for result in security_rating_data.json.results %}
          {% if result is mapping and ('unused' in result|string|lower or 'policy' in result|string|lower) %}
          {% set _ = found_unused.append(result) %}
          {% endif %}
          {% endfor %}
          {% endif %}
          
          {% if security_rating_data.json.securityRatingResults is defined %}
          {% for result in security_rating_data.json.securityRatingResults %}
          {% if result is mapping and result.recommendations is defined %}
          {% for rec in result.recommendations %}
          {% if rec is mapping and ('unused' in rec|string|lower or 'policy' in rec|string|lower) %}
          {% set _ = found_unused.append(rec) %}
          {% endif %}
          {% endfor %}
          {% endif %}
          {% endfor %}
          {% endif %}
          
          {% if found_unused|length > 0 %}
          🎯 找到 {{ found_unused|length }} 個相關項目:
          {% for item in found_unused[:3] %}
          
          📋 項目 {{ loop.index }}:
          {{ item | to_nice_json }}
          
          {% endfor %}
          {% else %}
          ⚠️ 未在明顯位置找到 unused policies 資料
          {% endif %}
          ======================================

    - name: 🏢 分析 Devices 資料 (尋找 Policy 資訊)
      debug:
        msg: |
          ========= 🏢 Devices 分析 =========
          {% if security_rating_data.json.devices is defined %}
          
          📊 設備總數: {{ security_rating_data.json.devices|length }}
          
          {% for device in security_rating_data.json.devices[:2] %}
          📱 Device {{ loop.index }}:
          {% if device is mapping %}
          - Keys: {{ device.keys()|list }}
          {% if device.serialNumber is defined %}
          - Serial: {{ device.serialNumber }}
          {% endif %}
          {% if device.deviceName is defined %}
          - Name: {{ device.deviceName }}
          {% endif %}
          {% if device.recommendations is defined %}
          - Recommendations: {{ device.recommendations|length }}
          
          🔍 檢查 Recommendations:
          {% for rec in device.recommendations[:3] %}
          {% if rec is mapping and ('unused' in rec|string|lower or 'policy' in rec|string|lower) %}
          🎯 找到 Policy 相關推薦！
          {{ rec | to_nice_json }}
          {% endif %}
          {% endfor %}
          {% endif %}
          {% endif %}
          
          {% endfor %}
          {% endif %}
          ===============================

    - name: 📝 完整資料結構展示 (關鍵部分)
      debug:
        msg: |
          ========= 📝 完整資料結構 =========
          
          🔍 如果上面沒找到 unused policies，請檢查完整結構:
          
          📊 所有可能包含 policy 資訊的欄位:
          {% for key, value in security_rating_data.json.items() %}
          {% if 'policy' in key|lower or 'recommendation' in key|lower or 'result' in key|lower %}
          - {{ key }}: {{ value|type_debug }} ({{ value|length if value is iterable and value is not string else 'N/A' }})
          {% endif %}
          {% endfor %}
          
          💡 建議下一步:
          1. 檢查 devices[].recommendations 中是否有 unused policies
          2. 查看 securityRatingResults[].recommendations
          3. 分析 results[] 陣列中的具體內容
          ===================================
