---
- name: FortiGate Unused Policies Extractor (Safe Version)
  hosts: localhost
  gather_facts: false
  vars:
    fortigate_api_url: "https://{{ fortigate_host }}:{{ fortigate_api_port | default('443') }}"
    
  tasks:
    - name: 🎯 獲取所有 Policy 資料
      uri:
        url: "{{ fortigate_api_url }}/api/v2/monitor/firewall/policy"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          vdom: "{{ vdom_name | default('root') }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: 30
      register: all_policies

    - name: 🔍 檢查第一個 Policy 的欄位結構
      debug:
        msg: |
          ========= 🔍 Policy 欄位結構分析 =========
          {% if all_policies.json.results | length > 0 %}
          📋 第一個 Policy 的可用欄位:
          {{ all_policies.json.results[0].keys() | list }}
          
          📊 範例資料:
          {% for key, value in all_policies.json.results[0].items() %}
          - {{ key }}: {{ value }}
          {% endfor %}
          {% endif %}
          =========================================

    - name: 🔍 安全篩選 Unused Policies
      set_fact:
        unused_policies: "{{ all_policies.json.results | selectattr('bytes', 'defined') | selectattr('packets', 'defined') | selectattr('bytes', 'equalto', 0) | selectattr('packets', 'equalto', 0) | list }}"

    - name: 📊 Policy 統計總覽
      debug:
        msg: |
          ========= 📊 Policy 統計總覽 =========
          🏢 VDOM: {{ vdom_name | default('root') }}
          📋 總 Policies: {{ all_policies.json.results | length }}
          🎯 Unused Policies: {{ unused_policies | length }}
          📊 Used Policies: {{ (all_policies.json.results | length) - (unused_policies | length) }}
          
          {% if all_policies.json.results | length > 0 %}
          📈 Unused 比例: {{ ((unused_policies | length / all_policies.json.results | length) * 100) | round(1) }}%
          {% endif %}
          ====================================

    - name: 🎯 顯示 Unused Policies 清單
      debug:
        msg: |
          ========= 🎯 Unused Policies 詳細清單 =========
          
          {% if unused_policies | length > 0 %}
          {% for policy in unused_policies | sort(attribute='policyid') %}
          
          📋 Policy {{ policy.policyid | default('N/A') }}:
          - Bytes: {{ policy.bytes | default('N/A') }}
          - Packets: {{ policy.packets | default('N/A') }}  
          - Hit Count: {{ policy.hit_count | default('N/A') }}
          - Session Count: {{ policy.session_count | default('N/A') }}
          - Active Sessions: {{ policy.active_sessions | default('N/A') }}
          - Last Used: {{ 'Never' if (policy.last_used | default(0)) == 0 else ((policy.last_used | int) | strftime('%Y-%m-%d %H:%M:%S')) }}
          - First Used: {{ 'Never' if (policy.first_used | default(0)) == 0 else ((policy.first_used | int) | strftime('%Y-%m-%d %H:%M:%S')) }}
          {% if policy.session_last_used is defined %}
          - Session Last Used: {{ 'Never' if policy.session_last_used == 0 else (policy.session_last_used | int | strftime('%Y-%m-%d %H:%M:%S')) }}
          {% endif %}
          
          {% endfor %}
          {% else %}
          ✅ 所有 policies 都有使用記錄！
          {% endif %}
          ===============================================

    - name: 📋 Unused Policies 摘要
      debug:
        msg: |
          ========= 📋 Unused Policies 摘要 =========
          
          {% if unused_policies | length > 0 %}
          {% set never_used = unused_policies | selectattr('last_used', 'defined') | selectattr('last_used', 'equalto', 0) | list %}
          {% set old_unused = unused_policies | selectattr('last_used', 'defined') | rejectattr('last_used', 'equalto', 0) | list %}
          
          📊 分類統計:
          - Never Used: {{ never_used | length }} policies
          - Previously Used (但現在未使用): {{ old_unused | length }} policies
          
          {% if never_used | length > 0 %}
          📋 Never Used Policy IDs: 
          {{ never_used | map(attribute='policyid') | list | sort | join(', ') }}
          {% endif %}
          
          📋 All Unused Policy IDs:
          {{ unused_policies | map(attribute='policyid') | list | sort | join(', ') }}
          
          {% else %}
          ✅ 沒有發現 unused policies
          {% endif %}
          =========================================

    # 生成安全的 CSV 格式輸出
    - name: 📄 生成 CSV 格式輸出
      debug:
        msg: |
          ========= 📄 CSV 格式輸出 =========
          
          Policy ID,Bytes,Packets,Hit Count,Session Count,Active Sessions,Last Used,First Used,Status
          {% for policy in unused_policies | sort(attribute='policyid') %}
          {{ policy.policyid | default('N/A') }},{{ policy.bytes | default(0) }},{{ policy.packets | default(0) }},{{ policy.hit_count | default('N/A') }},{{ policy.session_count | default('N/A') }},{{ policy.active_sessions | default('N/A') }},"{{ 'Never' if (policy.last_used | default(0)) == 0 else ((policy.last_used | int) | strftime('%Y-%m-%d %H:%M:%S')) }}","{{ 'Never' if (policy.first_used | default(0)) == 0 else ((policy.first_used | int) | strftime('%Y-%m-%d %H:%M:%S')) }}","{{ 'Never Used' if (policy.last_used | default(0)) == 0 else 'Previously Used' }}"
          {% endfor %}
          
          ===================================

    # 生成安全的 JSON 輸出
    - name: 📤 生成 JSON 格式輸出
      debug:
        msg: |
          ========= 📤 JSON 格式輸出 =========
          
          {
            "scan_info": {
              "vdom": "{{ vdom_name | default('root') }}",
              "scan_time": "{{ ansible_date_time.iso8601 }}",
              "fortigate_host": "{{ fortigate_host }}"
            },
            "summary": {
              "total_policies": {{ all_policies.json.results | length }},
              "unused_policies": {{ unused_policies | length }},
              "used_policies": {{ (all_policies.json.results | length) - (unused_policies | length) }}{% if all_policies.json.results | length > 0 %},
              "unused_percentage": {{ ((unused_policies | length / all_policies.json.results | length) * 100) | round(1) }}{% endif %}
            },
            "unused_policy_ids": {{ unused_policies | map(attribute='policyid') | list | sort }},
            "unused_policies_detail": [
              {% for policy in unused_policies | sort(attribute='policyid') %}
              {
                "policyid": {{ policy.policyid | default('null') }},
                "bytes": {{ policy.bytes | default(0) }},
                "packets": {{ policy.packets | default(0) }},
                "hit_count": {{ policy.hit_count | default('null') }},
                "session_count": {{ policy.session_count | default('null') }},
                "active_sessions": {{ policy.active_sessions | default('null') }},
                "last_used_timestamp": {{ policy.last_used | default(0) }},
                "last_used_readable": "{{ 'Never' if (policy.last_used | default(0)) == 0 else ((policy.last_used | int) | strftime('%Y-%m-%d %H:%M:%S')) }}",
                "first_used_timestamp": {{ policy.first_used | default(0) }},
                "first_used_readable": "{{ 'Never' if (policy.first_used | default(0)) == 0 else ((policy.first_used | int) | strftime('%Y-%m-%d %H:%M:%S')) }}",
                "status": "{{ 'Never Used' if (policy.last_used | default(0)) == 0 else 'Previously Used' }}"
              }{{ ',' if not loop.last else '' }}
              {% endfor %}
            ]
          }
          ===================================

    # 分析可用的時間欄位
    - name: 🕐 分析時間相關欄位
      debug:
        msg: |
          ========= 🕐 時間欄位分析 =========
          
          {% if unused_policies | length > 0 %}
          {% set sample_policy = unused_policies[0] %}
          
          📊 第一個 unused policy 的時間欄位:
          {% for key, value in sample_policy.items() %}
          {% if 'time' in key|lower or 'used' in key|lower or key in ['last_used', 'first_used', 'session_last_used', 'session_first_used'] %}
          - {{ key }}: {{ value }} {% if value != 0 and value is number %}({{ value | int | strftime('%Y-%m-%d %H:%M:%S') }}){% endif %}
          {% endif %}
          {% endfor %}
          
          🔍 建議使用的時間欄位: last_used, session_last_used
          {% endif %}
          ===================================

    - name: 🎯 執行完成
      debug:
        msg: |
          ========= 🎯 任務執行完成 =========
          
          ✅ 成功分析 FortiGate unused policies
          📊 總共檢查了 {{ all_policies.json.results | length }} 條 policies
          🎯 識別出 {{ unused_policies | length }} 個 unused policies
          
          {% if unused_policies | length > 0 %}
          📋 Unused Policy IDs: {{ unused_policies | map(attribute='policyid') | list | sort | join(', ') }}
          
          💡 建議後續動作:
          1. 檢查這些 policies 的配置和用途
          2. 考慮將它們設為 disabled 而不是直接刪除
          3. 定期執行此檢查以維持 policy 清潔度
          {% else %}
          🎉 太棒了！沒有發現 unused policies
          {% endif %}
          
          💾 資料已以多種格式輸出，可用於進一步分析
          =================================
