---
# =============================================================================
# FortiGate DHCP Reserved Address Delete Execute For Workflow Playbook  
# 用途：執行實際的MAC刪除操作，將配置還原為Reserved狀態
# 輸入：接收Preview步驟的workflow變數
# 輸出：執行結果和操作摘要
# =============================================================================

- name: FortiGate DHCP Delete Execute For Workflow v3.4
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # 接收workflow變數
    target_id: "{{ wf_target_id }}"
    target_ip: "{{ wf_target_ip }}"
    original_mac: "{{ wf_original_mac }}"
    reserved_mac: "{{ wf_reserved_mac }}"
    original_desc: "{{ wf_original_desc }}"
    dhcp_server_id: "{{ wf_server_id }}"
    delete_mac: "{{ wf_delete_mac }}"
    ip_fourth_octet: "{{ wf_ip_fourth_octet }}"
    first_digit: "{{ wf_first_digit }}"
    last_two_digits: "{{ wf_last_two_digits }}"
    
    # FortiGate連接參數
    fortigate_host: "{{ fortigate_host }}"
    fortigate_token: "{{ fortigate_access_token }}"
    vdom_name: "{{ fortigate_vdom | default('root') }}"
    
  tasks:
    # 參數驗證
    - name: "🔍 Validate Workflow Parameters"
      ansible.builtin.fail:
        msg: "從Workflow接收參數失敗！此Job Template僅應在Workflow中執行。"
      when: 
        - target_id is not defined or target_ip is not defined or reserved_mac is not defined

    # 顯示執行參數（單行格式）
    - name: "📋 FortiGate DHCP Delete Execute v3.4"
      ansible.builtin.debug:
        msg: "===========================================" 

    - name: "🚀 Execute Parameters"
      ansible.builtin.debug:
        msg: "🚀 執行模式 | 已通過人工確認 | 目標ID: {{ target_id }} | IP: {{ target_ip }} | Server: {{ dhcp_server_id }}"

    - name: "📊 Configuration Change"
      ansible.builtin.debug:
        msg: "📊 變更 | MAC: {{ original_mac }} → {{ reserved_mac }} | 描述: '{{ original_desc }}' → 'Reserved'"

    # MAC計算驗證
    - name: "🧮 MAC Calculation Verification"
      ansible.builtin.debug:
        msg: "🧮 驗證 | IP第四碼: {{ ip_fourth_octet }} | 分解: {{ first_digit }}+{{ last_two_digits }} | MAC: {{ reserved_mac }}"

    - name: "✅ MAC Calculation Status"
      ansible.builtin.debug:
        msg: "{{ '✅ MAC計算正確' if reserved_mac == 'ff:ff:ff:ff:f' + first_digit + ':' + last_two_digits else '❌ MAC計算錯誤' }}"

    # 執行前最終確認
    - name: "⚠️ Final Confirmation"
      ansible.builtin.debug:
        msg: "⚠️ 即將執行FortiGate API呼叫 | 配置ID: {{ target_id }} | 此操作將永久修改配置"

    # 執行API呼叫
    - name: "🔧 Execute MAC Delete Operation"
      ansible.builtin.uri:
        url: "https://{{ fortigate_host }}/api/v2/cmdb/system.dhcp/server/{{ dhcp_server_id }}/reserved-address/{{ target_id }}"
        method: PUT
        headers:
          Authorization: "Bearer {{ fortigate_token }}"
        body:
          ip: "{{ target_ip }}"
          mac: "{{ reserved_mac }}"
          description: "Reserved"
        body_format: json
        validate_certs: false
        status_code: 200
      register: delete_result

    # 成功結果顯示
    - name: "🎉 Operation Success Status"
      ansible.builtin.debug:
        msg: "✅ MAC刪除操作成功 | HTTP狀態: {{ delete_result.status }} | 配置已變更: {{ delete_result.json.revision_changed | default(false) }}"
      when: 
        - delete_result is defined
        - delete_result.status == 200

    - name: "🎉 Configuration Changes"
      ansible.builtin.debug:
        msg: "🎉 變更完成 | ID: {{ target_id }} | IP: {{ target_ip }} | MAC: {{ original_mac }}→{{ reserved_mac }} | 描述: Reserved"
      when: 
        - delete_result is defined
        - delete_result.status == 200

    # 失敗結果顯示
    - name: "❌ Operation Failed"
      ansible.builtin.debug:
        msg: "❌ MAC刪除操作失敗 | HTTP狀態: {{ delete_result.status | default('未知') }} | 錯誤: {{ delete_result.msg | default('未知') }}"
      when: 
        - delete_result is defined 
        - delete_result.status != 200

    # 最終摘要
    - name: "📊 Workflow Summary"
      ansible.builtin.debug:
        msg: "=========================================="

    - name: "📊 Final Result"
      ansible.builtin.debug:
        msg: "📊 最終結果 | MAC刪除: {{ '✅成功' if (delete_result.status == 200) else '❌失敗' }} | {{ delete_mac }}→{{ reserved_mac }} | IP: {{ target_ip }}"

    - name: "📊 Rule Applied"
      ansible.builtin.debug:
        msg: "📊 套用規則 | IP第四碼{{ ip_fourth_octet }} → MAC f{{ first_digit }}:{{ last_two_digits }} | 描述設為Reserved"

    - name: "📅 Completion Time"
      ansible.builtin.debug:
        msg: "📅 完成時間: {{ ansible_date_time.iso8601 | default('未知') }}"
