---
- name: FortiGate DHCP Delete Execute for Workflow
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # 接收workflow變數
    target_id: "{{ wf_target_id }}"
    target_ip: "{{ wf_target_ip }}"
    original_mac: "{{ wf_original_mac }}"
    reserved_mac: "{{ wf_reserved_mac }}"
    dhcp_server_id: "{{ wf_server_id }}"
    fortigate_host: "{{ fortigate_host }}"
    fortigate_token: "{{ fortigate_access_token }}"
    
  tasks:
    - name: "🔧 Execute Delete Operation"
      ansible.builtin.uri:
        url: "https://{{ fortigate_host }}/api/v2/cmdb/system.dhcp/server/{{ dhcp_server_id }}/reserved-address/{{ target_id }}"
        method: PUT
        headers:
          Authorization: "Bearer {{ fortigate_token }}"
        body:
          ip: "{{ target_ip }}"
          mac: "{{ reserved_mac }}"
          description: "Reserved"
        body_format: json
        validate_certs: false
        status_code: 200
      register: result

    - name: "🧮 Verify MAC Calculation (Corrected)"
      ansible.builtin.debug:
        msg: |
          🔍 MAC還原計算驗證：
          - IP: {{ target_ip }}
          - IP第四碼: {{ ip_fourth_octet }}
          - 第一位數字: {{ wf_first_digit }}
          - 後兩位數字: {{ wf_last_two_digits }}
          - 還原MAC: {{ reserved_mac }}
          - 預期MAC: ff:ff:ff:ff:f{{ wf_first_digit }}:{{ wf_last_two_digits }}
          - 計算正確: {{ '✅' if reserved_mac == 'ff:ff:ff:ff:f' + wf_first_digit + ':' + wf_last_two_digits else '❌' }}
