---
- name: Get FortiGate DHCP Reserved Addresses
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # 您可以將 DHCP Server 的 ID 放在這裡或是在 AWX Templates 的 Variables 中傳入 >>server_id: "4"
    dhcp_server_id: "{{ server_id | default('3') }}"

  tasks:
    - name: 獲取指定 DHCP Server 的保留位址列表
      ansible.builtin.uri:
        # API 路徑指向 system.dhcp server 下的 reserved-address
        url: "https://{{ lookup('env', 'FORTIGATE_HOST') }}/api/v2/cmdb/system.dhcp/server/{{ dhcp_server_id }}/reserved-address"
        method: GET
        headers:
          Authorization: "Bearer {{ lookup('env', 'FORTIGATE_API_TOKEN') }}"
        validate_certs: false
        status_code: 200
      register: result

    - name: 以 FortiGate CLI 格式顯示 DHCP 保留位址設定
      ansible.builtin.debug:
        # 使用 Jinja2 模板來動態產生 CLI 格式的輸出
        msg: |
          config system dhcp server
              edit {{ dhcp_server_id }}
                  config reserved-address
          {% for item in result.json.results %}
                      edit {{ item.id }}
                          set ip {{ item.ip }}
                          set mac {{ item.mac }}
                          set description "{{ item.description | default('', true) }}"
                      next
          {% endfor %}
                  end
              next
          end
      # 只有在成功獲取到結果時才顯示
      when: result.json.results is defined and result.json.results | length > 0
