---
- name: Retrieve all FortiGate firewall addresses
  hosts: fortigate_group # 替換為您的庫存組名或直接使用 all
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    # vdom 變數可以從庫存或 AWX 憑證中獲取，這裡作為示例
    vdom: "root"
  tasks:
    - name: Fetch all firewall addresses from FortiGate
      fortinet.fortios.fortios_configuration_fact:
        vdom: "{{ vdom }}"
        selector: firewall_address
        # access_token 將由 AWX 憑證中的 fortios_access_token 注入
      register: firewall_addresses_output

    - name: Display all firewall addresses
      debug:
        var: firewall_addresses_output.ansible_facts.fortios_firewall_address

