---
- name: Query FortiGate Unused Firewall Policies (Fixed Export)
  hosts: localhost
  gather_facts: true
  vars:
    fortigate_api_url: "https://{{ fortigate_host }}:{{ fortigate_api_port | default('443') }}"
    # 使用多種artifacts路徑嘗試
    artifacts_dir: "{{ ansible_job_id | default('default') }}"

  tasks:
    # ... 前面的查詢邏輯保持不變 ...

    # =================== 建立artifacts目錄（多種路徑） ===================
    - name: 建立artifacts目錄（方法1 - 標準路徑）
      file:
        path: "/tmp/artifacts"
        state: directory
        mode: '0755'
      ignore_errors: true
      when: export_to_file | default(false) | bool

    - name: 建立artifacts目錄（方法2 - 工作目錄）
      file:
        path: "{{ playbook_dir }}/artifacts"  
        state: directory
        mode: '0755'
      ignore_errors: true
      when: export_to_file | default(false) | bool

    - name: 建立artifacts目錄（方法3 - job目錄）
      file:
        path: "/tmp/{{ ansible_job_id | default('awx') }}"
        state: directory
        mode: '0755'
      ignore_errors: true
      when: export_to_file | default(false) | bool

    # =================== 檢查可用的目錄 ===================
    - name: 檢查artifacts目錄
      stat:
        path: "{{ item }}"
      register: dir_check
      loop:
        - "/tmp/artifacts"
        - "{{ playbook_dir }}/artifacts"
        - "/tmp/{{ ansible_job_id | default('awx') }}"
      when: export_to_file | default(false) | bool

    - name: 設定可用的artifacts路徑
      set_fact:
        final_artifacts_dir: "{{ item.item }}"
      loop: "{{ dir_check.results | default([]) }}"
      when: 
        - export_to_file | default(false) | bool
        - item.stat.exists | default(false)
        - final_artifacts_dir is not defined

    - name: 顯示使用的artifacts目錄
      debug:
        msg: "使用artifacts目錄: {{ final_artifacts_dir | default('/tmp/artifacts') }}"
      when: export_to_file | default(false) | bool

    # =================== 匯出檔案到多個位置 ===================
    - name: 匯出Policy清單CSV（多個位置）
      copy:
        content: |
          # FortiGate Policy Analysis Report
          # Generated: {{ ansible_date_time.iso8601 }}
          # VDOM: {{ vdom_name | default('root') }}
          # Total Policies: {{ total_policies }}
          # Enabled Policies: {{ enabled_count }}
          # Listed Policies: {{ filtered_policies | length }}
          
          policy_id,name,status,action,srcintf,dstintf,srcaddr,dstaddr,service,logtraffic,comments
          {% for policy in filtered_policies %}
          {{ policy.policy_id }},"{{ policy.name | replace('"', '""') }}",{{ policy.status }},{{ policy.action }},"{{ policy.srcintf }}","{{ policy.dstintf }}","{{ policy.srcaddr }}","{{ policy.dstaddr }}","{{ policy.service }}",{{ policy.logtraffic }},"{{ policy.comments | replace('"', '""') }}"
          {% endfor %}
        dest: "{{ item }}/policy_analysis_{{ ansible_date_time.epoch }}.csv"
        mode: '0644'
      loop:
        - "/tmp/artifacts"
        - "{{ playbook_dir }}/artifacts"
        - "/tmp"
      ignore_errors: true
      when: export_to_file | default(false) | bool

    - name: 生成Policy審查報告（多個位置）
      copy:
        content: |
          FortiGate Policy 審查報告
          ========================
          
          基本資訊:
          - 生成時間: {{ ansible_date_time.iso8601 }}
          - VDOM: {{ vdom_name | default('root') }}
          - FortiGate: {{ fortigate_host }}
          - AWX Job ID: {{ ansible_job_id | default('N/A') }}
          
          統計摘要:
          - 總Policy數量: {{ total_policies }}
          - 啟用Policy數量: {{ enabled_count }}
          - 停用Policy數量: {{ total_policies | int - enabled_count | int }}
          - 本次分析Policy數量: {{ filtered_policies | length }}
          
          Policy 詳細清單:
          {% for policy in filtered_policies %}
          
          {{ loop.index }}. Policy {{ policy.policy_id }}: {{ policy.name }}
             狀態: {{ policy.status }}
             動作: {{ policy.action }}
             來源介面: {{ policy.srcintf }}
             目的介面: {{ policy.dstintf }}
             來源地址: {{ policy.srcaddr }}
             目的地址: {{ policy.dstaddr }}
             服務: {{ policy.service }}
             日誌記錄: {{ policy.logtraffic }}
             備註: {{ policy.comments }}
          {% endfor %}
          
          建議清理CLI命令:
          ========================
          # 請人工審查後執行，務必先備份設定
          
          # 備份設定
          execute backup config management-station comment "policy-review-{{ ansible_date_time.date }}"
          
          # 停用Policy範例命令
          config firewall policy
          {% for policy in filtered_policies[:5] %}
              # Policy {{ policy.policy_id }}: {{ policy.name }}
              # edit {{ policy.policy_id }}
              #     set status disable
              #     set comments "{{ policy.comments }} [REVIEW-{{ ansible_date_time.date }}]"
              # next
          {% endfor %}
          end
          
          注意事項:
          ========================
          ⚠️ 所有變更請在維護時間窗口執行
          ⚠️ 建議先停用觀察，確認無影響後再刪除
          ⚠️ 保持變更記錄以便必要時回復
        dest: "{{ item }}/policy_review_report_{{ ansible_date_time.epoch }}.txt"
        mode: '0644'
      loop:
        - "/tmp/artifacts"
        - "{{ playbook_dir }}/artifacts"
        - "/tmp"
      ignore_errors: true
      when: export_to_file | default(false) | bool

    # =================== 直接在Job輸出中顯示檔案內容（備選方案） ===================
    - name: 顯示CSV內容（供複製使用）
      debug:
        msg: |
          ========= CSV檔案內容 (可直接複製) =========
          policy_id,name,status,action,srcintf,dstintf,srcaddr,dstaddr,service,logtraffic,comments
          {% for policy in filtered_policies %}
          {{ policy.policy_id }},"{{ policy.name | replace('"', '""') }}",{{ policy.status }},{{ policy.action }},"{{ policy.srcintf }}","{{ policy.dstintf }}","{{ policy.srcaddr }}","{{ policy.dstaddr }}","{{ policy.service }}",{{ policy.logtraffic }},"{{ policy.comments | replace('"', '""') }}"
          {% endfor %}
          ========= CSV檔案內容結束 =========
          
          您可以複製上述內容並儲存為 .csv 檔案
      when: 
        - export_to_file | default(false) | bool
        - show_content_in_log | default(false) | bool

    # =================== 檢查檔案是否成功建立 ===================
    - name: 檢查匯出檔案狀態
      stat:
        path: "{{ item }}/policy_analysis_{{ ansible_date_time.epoch }}.csv"
      register: file_check
      loop:
        - "/tmp/artifacts"
        - "{{ playbook_dir }}/artifacts"
        - "/tmp"
      when: export_to_file | default(false) | bool

    - name: 顯示檔案建立狀態
      debug:
        msg: |
          檔案建立狀態檢查:
          {% for result in file_check.results %}
          - {{ result.item }}/policy_analysis_{{ ansible_date_time.epoch }}.csv: {{ '✅ 存在' if result.stat.exists else '❌ 不存在' }}
          {% if result.stat.exists %}
            檔案大小: {{ result.stat.size }} bytes
          {% endif %}
          {% endfor %}
      when: export_to_file | default(false) | bool

    # =================== 提供下載指引 ===================
    - name: 下載指引
      debug:
        msg: |
          📁 檔案匯出完成！請嘗試以下方式取得檔案：
          
          方法1 - AWX Artifacts:
          - 到AWX Job詳情頁面查看 "Artifacts" 區塊
          - 如果沒有Artifacts區塊，請檢查AWX設定
          
          方法2 - 直接從容器複製:
          docker exec -it <awx_task_container> ls -la /tmp/artifacts/
          docker cp <awx_task_container>:/tmp/artifacts/policy_analysis_{{ ansible_date_time.epoch }}.csv .
          
          方法3 - 查看Job輸出:
          {% if show_content_in_log | default(false) %}
          - 上方已顯示CSV內容，可直接複製使用
          {% else %}
          - 重新執行Job並設定 show_content_in_log: true 來顯示檔案內容
          {% endif %}
          
          檔案名稱:
          - policy_analysis_{{ ansible_date_time.epoch }}.csv
          - policy_review_report_{{ ansible_date_time.epoch }}.txt
      when: export_to_file | default(false) | bool

    # =================== 最終報告 ===================
    - name: 查詢完成報告
      debug:
        msg: |
          🎯 Policy分析完成！
          
          📈 處理結果:
          - 分析了 {{ total_policies }} 個Policy
          - 符合條件的Policy: {{ filtered_policies | length }} 個
          
          {% if export_to_file | default(false) | bool %}
          📁 匯出狀態: 檔案已嘗試匯出到多個位置
          時間戳記: {{ ansible_date_time.epoch }}
          {% endif %}
          
          ⚠️ 如無法下載檔案，請設定 show_content_in_log: true 重新執行
