---
- name: Query FortiGate Unused Firewall Policies (READ ONLY)
  hosts: localhost
  gather_facts: false
  vars:
    fortigate_api_url: "https://{{ fortigate_host }}:{{ fortigate_api_port | default('443') }}"
    current_timestamp: "{{ ansible_date_time.epoch | int }}"
    threshold_timestamp: "{{ (current_timestamp | int) - ((months_threshold | default('6') | int) * 30 * 24 * 3600) }}"
    unused_policies: []
    never_used_policies: []
    total_policies: 0
    active_policies: 0
    read_only_mode: true

  tasks:
    # =================== 安全檢查 ===================
    - name: 安全提醒 - 此playbook為只讀模式
      debug:
        msg: |
          ⚠️  安全提醒 ⚠️
          此playbook僅執行查詢和報告生成，不會對FortiGate進行任何變更
          所有生成的CLI命令需要人工審查後手動執行
          ==========================================

    - name: 驗證只讀模式
      assert:
        that:
          - read_only_mode | default(true) | bool
          - not (auto_cleanup | default(false) | bool)
        fail_msg: "此playbook必須在只讀模式下運行"
        success_msg: "✅ 安全檢查通過，只讀模式已確認"

    # =================== 資料收集階段 ===================
    - name: 查詢所有Firewall Policy設定
      uri:
        url: "{{ fortigate_api_url }}/api/v2/cmdb/firewall/{{ policy_type | default('policy') }}"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          vdom: "{{ vdom_name | default('root') }}"
          format: "name|policyid|srcintf|dstintf|srcaddr|dstaddr|service|action|status|logtraffic|comments"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: "{{ fortigate_timeout | default('60') | int }}"
        status_code: [200]
      register: policy_config_result
      retries: "{{ fortigate_api_retries | default('3') | int }}"
      delay: "{{ fortigate_api_delay | default('5') | int }}"

    - name: 顯示找到的Policy數量
      debug:
        msg: "找到 {{ policy_config_result.json.results | length }} 個firewall policy"

    - name: 設定總policy數量
      set_fact:
        total_policies: "{{ policy_config_result.json.results | length }}"

    # =================== 查詢Policy統計資訊 ===================
    - name: 查詢Policy使用統計（批次處理）
      uri:
        url: "{{ fortigate_api_url }}/api/v2/monitor/firewall/policy/select"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          vdom: "{{ vdom_name | default('root') }}"
          policyid: "{{ item.policyid }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: "{{ fortigate_timeout | default('30') | int }}"
        status_code: [200, 424]  # 424表示policy不存在或無統計資料
      register: policy_stats_results
      loop: "{{ policy_config_result.json.results | default([]) }}"
      failed_when: false
      retries: 2
      delay: 1
      when: policy_config_result.json.results | length > 0

    - name: 顯示統計查詢進度
      debug:
        msg: "已查詢 {{ policy_stats_results.results | length }} 個policy的使用統計"

    # =================== 資料處理階段 ===================
    - name: 處理Policy資料並識別未使用的Policy
      set_fact:
        processed_policies: |
          [
          {% for config in policy_config_result.json.results %}
          {% set policy_id = config.policyid %}
          {% set stats_result = policy_stats_results.results | selectattr('item.policyid', 'equalto', policy_id) | first | default({}) %}
          {% set stats_data = stats_result.json | default({}) %}
          {% set last_used = stats_data.last_used | default(0) %}
          {% set hit_count = stats_data.hit_count | default(0) %}
          {% set bytes_count = stats_data.bytes | default(0) %}
          {% set packets_count = stats_data.packets | default(0) %}
          
          {
            "policy_id": "{{ policy_id }}",
            "name": "{{ config.name | default('Policy_' + policy_id) }}",
            "status": "{{ config.status | default('enable') }}",
            "action": "{{ config.action | default('accept') }}",
            "srcintf": {{ config.srcintf | default([]) | to_json }},
            "dstintf": {{ config.dstintf | default([]) | to_json }},
            "srcaddr": {{ config.srcaddr | default([]) | to_json }},
            "dstaddr": {{ config.dstaddr | default([]) | to_json }},
            "service": {{ config.service | default([]) | to_json }},
            "logtraffic": "{{ config.logtraffic | default('disable') }}",
            "comments": "{{ config.comments | default('') }}",
            "last_used": {{ last_used }},
            "last_used_readable": "{{ 'Never' if last_used == 0 else (last_used | int | strftime('%Y-%m-%d %H:%M:%S')) }}",
            "hit_count": {{ hit_count }},
            "bytes": {{ bytes_count }},
            "packets": {{ packets_count }},
            "days_since_last_used": {{ ((current_timestamp | int) - (last_used | int)) // 86400 if last_used | int > 0 else -1 }},
            "is_unused": {{ (last_used | int > 0 and last_used | int < threshold_timestamp | int) or (last_used | int == 0 and include_never_used | default(true)) }},
            "is_never_used": {{ last_used | int == 0 }},
            "is_enabled": {{ config.status | default('enable') == 'enable' }}
          }{% if not loop.last %},{% endif %}
          {% endfor %}
          ]

    - name: 過濾出未使用的Policy
      set_fact:
        unused_policies: "{{ processed_policies | selectattr('is_unused', 'equalto', true) | list }}"
        never_used_policies: "{{ processed_policies | selectattr('is_never_used', 'equalto', true) | list }}"
        active_policies: "{{ processed_policies | selectattr('is_enabled', 'equalto', true) | length }}"

    # 應用額外過濾條件
    - name: 應用進階過濾條件
      set_fact:
        filtered_unused_policies: |
          {% set filtered = [] %}
          {% for policy in unused_policies %}
          {% set skip_policy = false %}
          
          {# 排除指定的policy ID #}
          {% if filter_options.exclude_policy_ids | default([]) and policy.policy_id in filter_options.exclude_policy_ids %}
          {% set skip_policy = true %}
          {% endif %}
          
          {# 最小policy ID過濾 #}
          {% if filter_options.min_policy_id | default('') != '' and policy.policy_id | int < filter_options.min_policy_id | int %}
          {% set skip_policy = true %}
          {% endif %}
          
          {# 最大policy ID過濾 #}
          {% if filter_options.max_policy_id | default('') != '' and policy.policy_id | int > filter_options.max_policy_id | int %}
          {% set skip_policy = true %}
          {% endif %}
          
          {# Policy名稱模式過濾 #}
          {% if filter_options.policy_name_pattern | default('') != '' and not (policy.name | regex_search(filter_options.policy_name_pattern)) %}
          {% set skip_policy = true %}
          {% endif %}
          
          {# 是否包含停用的policy #}
          {% if not include_disabled | default(false) and not policy.is_enabled %}
          {% set skip_policy = true %}
          {% endif %}
          
          {% if not skip_policy %}
          {% set _ = filtered.append(policy) %}
          {% endif %}
          {% endfor %}
          {{ filtered }}

    # =================== 輸出階段 ===================
    - name: 顯示統計摘要
      debug:
        msg: |
          ========= FortiGate Unused Policy 查詢結果 =========
          VDOM: {{ vdom_name | default('root') }}
          查詢閾值: {{ months_threshold | default('6') }} 個月
          總Policy數量: {{ total_policies }}
          啟用的Policy: {{ active_policies }}
          超過{{ months_threshold }}個月未使用: {{ (filtered_unused_policies | rejectattr('is_never_used', 'equalto', true) | list | length) }}
          從未使用過: {{ (filtered_unused_policies | selectattr('is_never_used', 'equalto', true) | list | length) }}
          符合條件總數: {{ filtered_unused_policies | length }}
          ===============================================

    # 表格格式輸出
    - name: 表格格式輸出未使用的Policy
      debug:
        msg: |
          {% set unused_long_term = filtered_unused_policies | rejectattr('is_never_used', 'equalto', true) | list %}
          {% set unused_never = filtered_unused_policies | selectattr('is_never_used', 'equalto', true) | list %}
          
          {% if unused_long_term | length > 0 %}
          =================== 超過{{ months_threshold }}個月未使用的Policy ===================
          | Policy ID | Policy Name                | Status  | Last Used          | Days Ago | Hit Count | Action |
          |-----------|----------------------------|---------|--------------------|---------|-----------:|--------|
          {% for policy in unused_long_term %}
          | {{ "%-9s" | format(policy.policy_id) }} | {{ "%-26s" | format(policy.name[:26]) }} | {{ "%-7s" | format(policy.status) }} | {{ "%-18s" | format(policy.last_used_readable[:18]) }} | {{ "%7s" | format(policy.days_since_last_used) }} | {{ "%9s" | format(policy.hit_count) }} | {{ "%-6s" | format(policy.action) }} |
          {% endfor %}
          {% endif %}
          
          {% if unused_never | length > 0 and include_never_used | default(true) %}
          =================== 從未使用過的Policy ===================
          | Policy ID | Policy Name                | Status  | Hit Count | Action | Comments                |
          |-----------|----------------------------|---------|----------:|--------|-------------------------|
          {% for policy in unused_never %}
          | {{ "%-9s" | format(policy.policy_id) }} | {{ "%-26s" | format(policy.name[:26]) }} | {{ "%-7s" | format(policy.status) }} | {{ "%9s" | format(policy.hit_count) }} | {{ "%-6s" | format(policy.action) }} | {{ "%-23s" | format(policy.comments[:23]) }} |
          {% endfor %}
          {% endif %}
      when: output_format | default("table") == "table"

    # JSON格式輸出
    - name: JSON格式輸出
      debug:
        var: filtered_unused_policies
      when: output_format | default("table") == "json"

    # CSV格式輸出
    - name: CSV格式輸出
      debug:
        msg: |
          policy_id,name,status,action,last_used,days_since_last_used,hit_count,bytes,packets,srcintf,dstintf,srcaddr,dstaddr,service,comments
          {% for policy in filtered_unused_policies %}
          {{ policy.policy_id }},"{{ policy.name | replace('"', '""') }}",{{ policy.status }},{{ policy.action }},{{ policy.last_used_readable }},{{ policy.days_since_last_used }},{{ policy.hit_count }},{{ policy.bytes }},{{ policy.packets }},"{{ policy.srcintf | join(';') }}","{{ policy.dstintf | join(';') }}","{{ policy.srcaddr | join(';') }}","{{ policy.dstaddr | join(';') }}","{{ policy.service | join(';') }}","{{ policy.comments | replace('"', '""') }}"
          {% endfor %}
      when: output_format | default("table") == "csv"

    # =================== 檔案匯出（AWX Artifacts） ===================
    - name: 建立artifacts目錄
      file:
        path: "{{ playbook_dir }}/artifacts"
        state: directory
      when: export_to_file | default(false) | bool

    - name: 匯出CSV格式報告
      copy:
        content: |
          # FortiGate Unused Policy Report
          # Generated: {{ ansible_date_time.iso8601 }}
          # VDOM: {{ vdom_name | default('root') }}
          # Threshold: {{ months_threshold | default('6') }} months
          # Total Policies: {{ total_policies }}
          # Unused Policies Found: {{ filtered_unused_policies | length }}
          
          policy_id,name,status,action,last_used,days_since_last_used,hit_count,bytes,packets,srcintf,dstintf,srcaddr,dstaddr,service,comments
          {% for policy in filtered_unused_policies %}
          {{ policy.policy_id }},"{{ policy.name | replace('"', '""') }}",{{ policy.status }},{{ policy.action }},{{ policy.last_used_readable }},{{ policy.days_since_last_used }},{{ policy.hit_count }},{{ policy.bytes }},{{ policy.packets }},"{{ policy.srcintf | join(';') }}","{{ policy.dstintf | join(';') }}","{{ policy.srcaddr | join(';') }}","{{ policy.dstaddr | join(';') }}","{{ policy.service | join(';') }}","{{ policy.comments | replace('"', '""') }}"
          {% endfor %}
        dest: "{{ playbook_dir }}/artifacts/unused_policies_{{ ansible_date_time.epoch }}.csv"
      when: export_to_file | default(false) | bool

    - name: 匯出JSON格式報告
      copy:
        content: |
          {
            "report_info": {
              "generated_at": "{{ ansible_date_time.iso8601 }}",
              "vdom": "{{ vdom_name | default('root') }}",
              "threshold_months": {{ months_threshold | default('6') }},
              "total_policies": {{ total_policies }},
              "unused_policies_count": {{ filtered_unused_policies | length }}
            },
            "unused_policies": {{ filtered_unused_policies | to_nice_json }}
          }
        dest: "{{ playbook_dir }}/artifacts/unused_policies_{{ ansible_date_time.epoch }}.json"
      when: export_to_file | default(false) | bool

    # =================== 生成清理腳本（僅供參考） ===================
    - name: 生成清理建議腳本（僅供參考，不會自動執行）
      copy:
        content: |
          #!/bin/bash
          # ⚠️⚠️⚠️ 重要安全提醒 ⚠️⚠️⚠️
          # 此腳本由AWX自動生成，僅供參考
          # 請務必人工審查每個Policy後再執行
          # 建議先在測試環境驗證
          # ================================
          
          echo "此腳本不會自動執行，請人工複製以下命令到FortiGate CLI"
          echo "建議執行步驟："
          echo "1. 仔細審查每個要停用的Policy"
          echo "2. 先在測試環境執行"
          echo "3. 做好備份"
          echo "4. 分批次執行，觀察影響"
          echo "================================"
          echo ""
          
          # 以下為建議命令，請人工複製執行：
          
          echo "# === 第一階段：停用長期未使用的Policy ==="
          {% for policy in (filtered_unused_policies | rejectattr('is_never_used', 'equalto', true) | selectattr('is_enabled', 'equalto', true) | list) %}
          echo "# Policy {{ policy.policy_id }}: {{ policy.name }}"
          echo "# 最後使用: {{ policy.last_used_readable }}"
          echo "# 未使用天數: {{ policy.days_since_last_used }}"
          echo "# 來源: {{ policy.srcaddr | join(',') }}"
          echo "# 目的: {{ policy.dstaddr | join(',') }}"
          echo "# 服務: {{ policy.service | join(',') }}"
          echo ""
          echo "config firewall policy"
          echo "    edit {{ policy.policy_id }}"
          echo "        set status disable"
          echo "        set comments \"{{ policy.comments }} [DISABLED-{{ ansible_date_time.date }}-UNUSED-{{ policy.days_since_last_used }}DAYS]\""
          echo "    next"
          echo "end"
          echo "echo 'Policy {{ policy.policy_id }} 已停用，請觀察是否有影響'"
          echo "sleep 5"
          echo ""
          {% endfor %}
          
          echo ""
          echo "# === 第二階段：觀察期後考慮刪除（需要額外確認） ==="
          {% for policy in (filtered_unused_policies | selectattr('is_never_used', 'equalto', true) | list)[:5] %}
          echo "# 從未使用的Policy {{ policy.policy_id }}: {{ policy.name }}"
          echo "# 建議先停用觀察30天後再考慮刪除"
          echo "# config firewall policy"
          echo "#     delete {{ policy.policy_id }}"
          echo "# end"
          echo ""
          {% endfor %}
          
          echo "================================"
          echo "⚠️ 執行前請確認："
          echo "1. 已做好設定備份"
          echo "2. 在維護時間窗口執行"
          echo "3. 有回復計劃"
          echo "4. 相關人員已知悉"
          echo "================================"
        dest: "{{ playbook_dir }}/artifacts/MANUAL_cleanup_commands_{{ ansible_date_time.epoch }}.sh"
        mode: '0644'  # 注意：設為只讀，防止意外執行
      when: 
        - export_to_file | default(false) | bool
        - filtered_unused_policies | length > 0

    - name: 顯示artifacts檔案位置
      debug:
        msg: |
          ========= 匯出檔案完成 =========
          檔案已儲存到AWX artifacts目錄:
          - unused_policies_{{ ansible_date_time.epoch }}.csv
          - unused_policies_{{ ansible_date_time.epoch }}.json
          - MANUAL_cleanup_commands_{{ ansible_date_time.epoch }}.sh
          
          您可以在AWX Job詳情頁面的"Artifacts"區塊下載這些檔案
          =============================
      when: export_to_file | default(false) | bool

    # =================== 最終安全提醒 ===================
    - name: ⚠️ 最終安全提醒
      debug:
        msg: |
          ========= ⚠️ 重要安全提醒 ⚠️ =========
          
          此查詢已完成，找到 {{ filtered_unused_policies | length }} 個符合條件的Policy
          
          {% if export_to_file | default(false) | bool %}
          生成的檔案包含：
          1. 📊 分析報告 (unused_policies_xxx.csv/json)
          2. 🔧 CLI腳本 (MANUAL_cleanup_commands_xxx.sh)
          {% endif %}
          
          ⚠️ 重要：
          - 所有CLI命令都需要人工審查和執行
          - 建議分階段執行，每階段間隔觀察
          - 執行前請做好備份和回復計劃
          - 在維護時間窗口執行
          
          ❌ 此playbook絕不會自動執行任何變更
          ✅ 所有變更都需要人工確認和執行
          =====================================
