---
- name: Query FortiGate Unused Policies (Real Usage Check)
  hosts: localhost
  gather_facts: true
  vars:
    fortigate_api_url: "https://{{ fortigate_host }}:{{ fortigate_api_port | default('443') }}"
    current_timestamp: "{{ ansible_date_time.epoch | int }}"
    threshold_timestamp: "{{ (ansible_date_time.epoch | int) - ((months_threshold | default('6') | int) * 30 * 24 * 3600) }}"

  tasks:
    - name: 安全提醒
      debug:
        msg: "🔍 開始查詢FortiGate Policy使用情況 (真實統計資料)"

    # =================== 查詢Policy設定 ===================
    - name: 查詢所有Firewall Policy設定
      uri:
        url: "{{ fortigate_api_url }}/api/v2/cmdb/firewall/{{ policy_type | default('policy') }}"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          vdom: "{{ vdom_name | default('root') }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: "{{ fortigate_timeout | default('60') | int }}"
      register: policy_configs
      retries: "{{ fortigate_api_retries | default('3') | int }}"
      delay: "{{ fortigate_api_delay | default('5') | int }}"

    - name: 顯示找到的Policy數量
      debug:
        msg: "✅ 找到 {{ policy_configs.json.results | length }} 個Policy，開始查詢使用統計..."

    # =================== 查詢Policy統計資料 ===================
    - name: 查詢Policy使用統計（批次處理，限制數量避免timeout）
      uri:
        url: "{{ fortigate_api_url }}/api/v2/monitor/firewall/policy/select"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          vdom: "{{ vdom_name | default('root') }}"
          policyid: "{{ item.policyid }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: "{{ fortigate_timeout | default('30') | int }}"
        status_code: [200, 400, 424]  # 424: policy不存在或無統計
      register: policy_stats_raw
      loop: "{{ policy_configs.json.results[:batch_size | default(50) | int] }}"
      failed_when: false
      no_log: "{{ suppress_stats_log | default(true) }}"
      when: policy_configs.json.results | length > 0

    - name: 顯示統計查詢進度
      debug:
        msg: |
          📊 統計查詢完成:
          - 查詢了 {{ policy_stats_raw.results | length }} 個Policy
          - 成功取得統計: {{ policy_stats_raw.results | selectattr('status', 'equalto', 200) | list | length }} 個
          - 無統計資料: {{ policy_stats_raw.results | selectattr('status', 'equalto', 424) | list | length }} 個

    # =================== 處理使用情況資料 ===================
    - name: 分析Policy使用情況
      set_fact:
        analyzed_policies: "{{ policy_analysis }}"
      vars:
        policy_analysis: |
          [
          {% for config in policy_configs.json.results[:batch_size | default(50) | int] %}
          {% set policy_id = config.policyid | string %}
          {% set stats_result = policy_stats_raw.results | selectattr('item.policyid', 'equalto', config.policyid) | first | default({}) %}
          {% set stats_data = stats_result.json | default({}) %}
          
          {% set last_used = stats_data.last_used | default(0) | int %}
          {% set hit_count = stats_data.hit_count | default(0) | int %}
          {% set bytes_sent = stats_data.bytes | default(0) | int %}
          {% set packets = stats_data.packets | default(0) | int %}
          
          {% set days_unused = ((current_timestamp | int) - last_used) // 86400 if last_used > 0 else -1 %}
          {% set is_never_used = last_used == 0 %}
          {% set is_long_unused = last_used > 0 and last_used < threshold_timestamp | int %}
          {% set is_unused = is_long_unused or (is_never_used and include_never_used | default(true)) %}
          
          {
            "policy_id": "{{ policy_id }}",
            "name": "{{ config.name | default('Policy_' + policy_id) }}",
            "status": "{{ config.status | default('enable') }}",
            "action": "{{ config.action | default('accept') }}",
            "srcintf": "{{ config.srcintf | default([]) | join(',') }}",
            "dstintf": "{{ config.dstintf | default([]) | join(',') }}",
            "srcaddr": "{{ config.srcaddr | default([]) | join(',') }}",
            "dstaddr": "{{ config.dstaddr | default([]) | join(',') }}",
            "service": "{{ config.service | default([]) | join(',') }}",
            "comments": "{{ config.comments | default('') }}",
            "last_used_timestamp": {{ last_used }},
            "last_used_readable": "{{ 'Never' if is_never_used else (last_used | int | strftime('%Y-%m-%d %H:%M:%S')) }}",
            "days_since_last_used": {{ days_unused }},
            "hit_count": {{ hit_count }},
            "bytes_total": {{ bytes_sent }},
            "packets_total": {{ packets }},
            "is_never_used": {{ is_never_used }},
            "is_long_unused": {{ is_long_unused }},
            "is_unused": {{ is_unused }},
            "is_enabled": {{ config.status | default('enable') == 'enable' }},
            "has_stats": {{ stats_result.status | default(424) == 200 }}
          }{% if not loop.last %},{% endif %}
          {% endfor %}
          ]

    # =================== 過濾未使用的Policy ===================
    - name: 過濾未使用的Policy
      set_fact:
        unused_policies: "{{ analyzed_policies | selectattr('is_unused', 'equalto', true) | list }}"
        never_used_policies: "{{ analyzed_policies | selectattr('is_never_used', 'equalto', true) | list }}"
        long_unused_policies: "{{ analyzed_policies | selectattr('is_long_unused', 'equalto', true) | list }}"
        total_analyzed: "{{ analyzed_policies | length }}"
        policies_with_stats: "{{ analyzed_policies | selectattr('has_stats', 'equalto', true) | length }}"

    # =================== 顯示使用情況分析 ===================
    - name: 顯示使用情況分析
      debug:
        msg: |
          ========= Policy使用情況分析 =========
          VDOM: {{ vdom_name | default('root') }}
          分析時間: {{ ansible_date_time.iso8601 }}
          未使用閾值: {{ months_threshold | default('6') }} 個月
          
          📊 統計摘要:
          - 分析Policy數量: {{ total_analyzed }}
          - 有統計資料的Policy: {{ policies_with_stats }}
          - 超過{{ months_threshold }}個月未使用: {{ long_unused_policies | length }}
          - 從未使用過: {{ never_used_policies | length }}
          - 總計未使用: {{ unused_policies | length }}
          
          🔍 資料完整性:
          - 統計資料覆蓋率: {{ (policies_with_stats | int * 100 / total_analyzed | int) | round(1) }}%
          {% if policies_with_stats | int < total_analyzed | int %}
          - ⚠️ 注意: {{ total_analyzed | int - policies_with_stats | int }} 個Policy無統計資料
          {% endif %}
          =====================================

    # =================== 顯示未使用Policy詳情 ===================
    - name: 顯示長期未使用的Policy
      debug:
        msg: |
          ========= 超過{{ months_threshold }}個月未使用的Policy =========
          {% for policy in long_unused_policies[:15] %}
          {{ loop.index }}. Policy {{ policy.policy_id }}: {{ policy.name }}
             狀態: {{ policy.status }} | 最後使用: {{ policy.last_used_readable }}
             未使用天數: {{ policy.days_since_last_used }} 天
             點擊次數: {{ policy.hit_count }} | 流量: {{ (policy.bytes_total / 1024 / 1024) | round(2) }} MB
             來源: {{ policy.srcaddr[:50] }}{{ '...' if policy.srcaddr | length > 50 else '' }}
             目的: {{ policy.dstaddr[:50] }}{{ '...' if policy.dstaddr | length > 50 else '' }}
             服務: {{ policy.service }}
          {% endfor %}
          {% if long_unused_policies | length > 15 %}
          ... 還有 {{ long_unused_policies | length - 15 }} 個長期未使用的Policy
          {% endif %}
          =============================================
      when: long_unused_policies | length > 0

    - name: 顯示從未使用的Policy
      debug:
        msg: |
          ========= 從未使用過的Policy =========
          {% for policy in never_used_policies[:15] %}
          {{ loop.index }}. Policy {{ policy.policy_id }}: {{ policy.name }}
             狀態: {{ policy.status }} | 點擊次數: {{ policy.hit_count }}
             來源: {{ policy.srcaddr[:50] }}{{ '...' if policy.srcaddr | length > 50 else '' }}
             目的: {{ policy.dstaddr[:50] }}{{ '...' if policy.dstaddr | length > 50 else '' }}
             服務: {{ policy.service }}
             備註: {{ policy.comments }}
          {% endfor %}
          {% if never_used_policies | length > 15 %}
          ... 還有 {{ never_used_policies | length - 15 }} 個從未使用的Policy
          {% endif %}
          ===================================
      when: never_used_policies | length > 0

    # =================== 匯出詳細資料 ===================
    - name: 輸出完整未使用Policy CSV資料
      debug:
        msg: |
          ========= 未使用Policy完整資料 (CSV格式) =========
          
          ## 檔名建議: unused_policies_{{ months_threshold }}months_{{ ansible_date_time.epoch }}.csv
          
          policy_id,name,status,action,last_used,days_unused,hit_count,bytes_mb,packets,srcintf,dstintf,srcaddr,dstaddr,service,usage_type,comments
          {% for policy in unused_policies %}
          {{ policy.policy_id }},"{{ policy.name | replace('"', '""') }}",{{ policy.status }},{{ policy.action }},{{ policy.last_used_readable }},{{ policy.days_since_last_used }},{{ policy.hit_count }},{{ (policy.bytes_total / 1024 / 1024) | round(2) }},{{ policy.packets_total }},"{{ policy.srcintf }}","{{ policy.dstintf }}","{{ policy.srcaddr }}","{{ policy.dstaddr }}","{{ policy.service }}","{{ 'Never Used' if policy.is_never_used else 'Long Unused' }}","{{ policy.comments | replace('"', '""') }}"
          {% endfor %}
          
          ========= CSV資料結束 =========
      when: unused_policies | length > 0

    # =================== 生成清理建議 ===================
    - name: 生成清理建議CLI命令
      debug:
        msg: |
          ========= 清理建議CLI命令 =========
          
          # FortiGate Policy清理腳本
          # 基於 {{ months_threshold | default('6') }} 個月使用情況分析
          # 生成時間: {{ ansible_date_time.iso8601 }}
          
          # === 備份設定 ===
          execute backup config management-station comment "unused-policy-cleanup-{{ ansible_date_time.date }}"
          
          # === 第一階段: 停用從未使用的Policy ===
          config firewall policy
          {% for policy in never_used_policies[:10] %}
          {% if policy.is_enabled %}
              # Policy {{ policy.policy_id }}: {{ policy.name }} (從未使用)
              edit {{ policy.policy_id }}
                  set status disable
                  set comments "{{ policy.comments }} [NEVER-USED-DISABLED-{{ ansible_date_time.date }}]"
              next
          {% endif %}
          {% endfor %}
          end
          
          # === 第二階段: 停用長期未使用的Policy ===
          config firewall policy
          {% for policy in long_unused_policies[:10] %}
          {% if policy.is_enabled %}
              # Policy {{ policy.policy_id }}: {{ policy.name }} ({{ policy.days_since_last_used }}天未使用)
              edit {{ policy.policy_id }}
                  set status disable  
                  set comments "{{ policy.comments }} [UNUSED-{{ policy.days_since_last_used }}DAYS-DISABLED-{{ ansible_date_time.date }}]"
              next
          {% endif %}
          {% endfor %}
          end
          
          # === 驗證命令 ===
          show firewall policy | grep disable
          diagnose firewall iprope show 100000 | head -20
          
          ========= CLI命令結束 =========
          
          ⚠️ 執行建議:
          1. 先執行第一階段，觀察1週
          2. 無問題後執行第二階段，觀察1個月
          3. 確認無影響後考慮刪除
      when: unused_policies | length > 0

    # =================== 最終報告 ===================
    - name: 任務完成報告
      debug:
        msg: |
          🎯 未使用Policy分析完成！
          
          📊 關鍵發現:
          - 分析了 {{ total_analyzed }} 個Policy (批次大小限制)
          - 找到 {{ unused_policies | length }} 個未使用的Policy
          - 其中 {{ never_used_policies | length }} 個從未使用
          - 其中 {{ long_unused_policies | length }} 個超過{{ months_threshold }}個月未使用
          
          💾 資料品質:
          - {{ policies_with_stats }} 個Policy有完整統計資料
          {% if total_analyzed >= 50 %}
          - ⚠️ 本次只分析前50個Policy (可調整batch_size)
          {% endif %}
          
          💡 後續建議:
          1. 複製CSV資料進行詳細分析
          2. 與業務團隊確認Policy必要性
          3. 分階段執行清理建議
          4. 持續監控Policy使用情況
          
          ⚠️ 重要提醒:
          - 基於實際統計資料的分析結果
          - 所有變更請在維護時間執行
          - 建議先停用觀察再刪除
