---
- name: Query FortiGate Unused Firewall Policies (READ ONLY)
  hosts: localhost
  gather_facts: false
  vars:
    fortigate_api_url: "https://{{ fortigate_host }}:{{ fortigate_api_port | default('443') }}"
    current_timestamp: "{{ ansible_date_time.epoch | int }}"
    threshold_timestamp: "{{ (current_timestamp | int) - ((months_threshold | default('6') | int) * 30 * 24 * 3600) }}"
    read_only_mode: true

  tasks:
    # =================== 安全檢查 ===================
    - name: 安全提醒 - 此playbook為只讀模式
      debug:
        msg: |
          ⚠️  安全提醒 ⚠️
          此playbook僅執行查詢和報告生成，不會對FortiGate進行任何變更
          所有生成的CLI命令需要人工審查後手動執行

    # =================== 資料收集階段 ===================
    - name: 查詢所有Firewall Policy設定
      uri:
        url: "{{ fortigate_api_url }}/api/v2/cmdb/firewall/{{ policy_type | default('policy') }}"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          vdom: "{{ vdom_name | default('root') }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: "{{ fortigate_timeout | default('60') | int }}"
        status_code: [200]
      register: policy_config_result
      retries: "{{ fortigate_api_retries | default('3') | int }}"
      delay: "{{ fortigate_api_delay | default('5') | int }}"

    - name: 顯示找到的Policy數量
      debug:
        msg: "找到 {{ policy_config_result.json.results | length }} 個firewall policy，開始查詢使用統計..."

    # =================== 查詢Policy統計（簡化版） ===================
    - name: 查詢Policy使用統計
      uri:
        url: "{{ fortigate_api_url }}/api/v2/monitor/firewall/policy/select"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          vdom: "{{ vdom_name | default('root') }}"
          policyid: "{{ item.policyid }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: "{{ fortigate_timeout | default('15') | int }}"
        status_code: [200, 424]
      register: policy_stats_results
      loop: "{{ policy_config_result.json.results | default([]) }}"
      failed_when: false
      no_log: true  # 減少log輸出
      when: policy_config_result.json.results | length > 0

    - name: 統計查詢完成
      debug:
        msg: "統計查詢完成，開始分析資料..."

    # =================== 資料處理階段（修正版） ===================
    - name: 初始化處理變數
      set_fact:
        processed_policies: []
        policy_counter: 0

    - name: 處理每個Policy的資料
      set_fact:
        processed_policies: "{{ processed_policies + [policy_data] }}"
        policy_counter: "{{ policy_counter | int + 1 }}"
      vars:
        config_item: "{{ policy_config_result.json.results[policy_counter | int] }}"
        policy_id: "{{ config_item.policyid | string }}"
        stats_item: "{{ policy_stats_results.results[policy_counter | int] if policy_stats_results.results is defined else {} }}"
        stats_data: "{{ stats_item.json | default({}) }}"
        last_used: "{{ stats_data.last_used | default(0) | int }}"
        hit_count: "{{ stats_data.hit_count | default(0) | int }}"
        bytes_count: "{{ stats_data.bytes | default(0) | int }}"
        packets_count: "{{ stats_data.packets | default(0) | int }}"
        days_ago: "{{ ((current_timestamp | int) - last_used) // 86400 if last_used > 0 else -1 }}"
        is_never_used: "{{ last_used == 0 }}"
        is_old_unused: "{{ last_used > 0 and last_used < (threshold_timestamp | int) }}"
        policy_data:
          policy_id: "{{ policy_id }}"
          name: "{{ config_item.name | default('Policy_' + policy_id) }}"
          status: "{{ config_item.status | default('enable') }}"
          action: "{{ config_item.action | default('accept') }}"
          srcintf: "{{ config_item.srcintf | default([]) | join(',') }}"
          dstintf: "{{ config_item.dstintf | default([]) | join(',') }}"
          srcaddr: "{{ config_item.srcaddr | default([]) | join(',') }}"
          dstaddr: "{{ config_item.dstaddr | default([]) | join(',') }}"
          service: "{{ config_item.service | default([]) | join(',') }}"
          logtraffic: "{{ config_item.logtraffic | default('disable') }}"
          comments: "{{ config_item.comments | default('') }}"
          last_used: "{{ last_used }}"
          last_used_readable: "{{ 'Never' if is_never_used else (last_used | int | strftime('%Y-%m-%d %H:%M:%S')) }}"
          hit_count: "{{ hit_count }}"
          bytes: "{{ bytes_count }}"
          packets: "{{ packets_count }}"
          days_since_last_used: "{{ days_ago }}"
          is_unused: "{{ is_old_unused or (is_never_used and (include_never_used | default(true))) }}"
          is_never_used: "{{ is_never_used }}"
          is_enabled: "{{ config_item.status | default('enable') == 'enable' }}"
      loop: "{{ range(0, policy_config_result.json.results | length) | list }}"
      loop_control:
        index_var: policy_counter
      no_log: true

    # =================== 過濾和統計 ===================
    - name: 過濾未使用的Policy
      set_fact:
        all_unused_policies: "{{ processed_policies | selectattr('is_unused', 'equalto', true) | list }}"

    - name: 應用進階過濾條件
      set_fact:
        filtered_unused_policies: "{{ all_unused_policies | select_policies }}"
      vars:
        filter:
          exclude_policy_ids: "{{ filter_options.exclude_policy_ids | default([]) }}"
          min_policy_id: "{{ filter_options.min_policy_id | default('') }}"
          max_policy_id: "{{ filter_options.max_policy_id | default('') }}"
          policy_name_pattern: "{{ filter_options.policy_name_pattern | default('') }}"
          include_disabled: "{{ include_disabled | default(false) }}"

    # 使用自定義filter
    - name: 手動過濾Policy
      set_fact:
        filtered_unused_policies: "{{ final_filtered }}"
      vars:
        final_filtered: |
          [
          {% for policy in all_unused_policies %}
          {% set skip_policy = false %}
          {% if filter_options.exclude_policy_ids | default([]) and policy.policy_id in filter_options.exclude_policy_ids %}
          {% set skip_policy = true %}
          {% endif %}
          {% if filter_options.min_policy_id | default('') != '' and policy.policy_id | int < filter_options.min_policy_id | int %}
          {% set skip_policy = true %}
          {% endif %}
          {% if filter_options.max_policy_id | default('') != '' and policy.policy_id | int > filter_options.max_policy_id | int %}
          {% set skip_policy = true %}
          {% endif %}
          {% if not include_disabled | default(false) and not policy.is_enabled %}
          {% set skip_policy = true %}
          {% endif %}
          {% if not skip_policy %}
          {{ policy | to_json }}{% if not loop.last %},{% endif %}
          {% endif %}
          {% endfor %}
          ]

    # =================== 統計摘要 ===================
    - name: 計算統計數據
      set_fact:
        total_policies: "{{ processed_policies | length }}"
        active_policies: "{{ processed_policies | selectattr('is_enabled', 'equalto', true) | length }}"
        unused_long_term: "{{ filtered_unused_policies | rejectattr('is_never_used', 'equalto', true) | list }}"
        unused_never: "{{ filtered_unused_policies | selectattr('is_never_used', 'equalto', true) | list }}"

    - name: 顯示統計摘要
      debug:
        msg: |
          ========= FortiGate Unused Policy 查詢結果 =========
          VDOM: {{ vdom_name | default('root') }}
          查詢閾值: {{ months_threshold | default('6') }} 個月
          總Policy數量: {{ total_policies }}
          啟用的Policy: {{ active_policies }}
          超過{{ months_threshold }}個月未使用: {{ unused_long_term | length }}
          從未使用過: {{ unused_never | length }}
          符合條件總數: {{ filtered_unused_policies | length }}
          ===============================================

    # =================== 結果輸出 ===================
    - name: 顯示長期未使用的Policy
      debug:
        msg: |
          =================== 超過{{ months_threshold }}個月未使用的Policy ===================
          {% for policy in unused_long_term %}
          Policy {{ policy.policy_id }}: {{ policy.name }}
            狀態: {{ policy.status }} | 動作: {{ policy.action }}
            最後使用: {{ policy.last_used_readable }} ({{ policy.days_since_last_used }}天前)
            點擊數: {{ policy.hit_count }} | 流量: {{ policy.bytes }}字節
            來源介面: {{ policy.srcintf }} -> 目的介面: {{ policy.dstintf }}
            來源地址: {{ policy.srcaddr }}
            目的地址: {{ policy.dstaddr }}
            服務: {{ policy.service }}
            備註: {{ policy.comments }}
          ---
          {% endfor %}
      when: 
        - unused_long_term | length > 0
        - output_format | default("table") == "table"

    - name: 顯示從未使用的Policy
      debug:
        msg: |
          =================== 從未使用過的Policy ===================
          {% for policy in unused_never %}
          Policy {{ policy.policy_id }}: {{ policy.name }}
            狀態: {{ policy.status }} | 動作: {{ policy.action }}
            來源介面: {{ policy.srcintf }} -> 目的介面: {{ policy.dstintf }}
            來源地址: {{ policy.srcaddr }}
            目的地址: {{ policy.dstaddr }}
            服務: {{ policy.service }}
            備註: {{ policy.comments }}
          ---
          {% endfor %}
      when: 
        - unused_never | length > 0
        - include_never_used | default(true)
        - output_format | default("table") == "table"

    # JSON格式輸出（簡化）
    - name: JSON格式輸出
      debug:
        var: filtered_unused_policies
      when: output_format | default("table") == "json"

    # =================== 檔案匯出 ===================
    - name: 建立artifacts目錄
      file:
        path: "{{ playbook_dir }}/artifacts"
        state: directory
      when: export_to_file | default(false) | bool

    - name: 匯出CSV格式報告
      copy:
        content: |
          # FortiGate Unused Policy Report
          # Generated: {{ ansible_date_time.iso8601 }}
          # VDOM: {{ vdom_name | default('root') }}
          # Threshold: {{ months_threshold | default('6') }} months
          # Total Policies: {{ total_policies }}
          # Unused Policies Found: {{ filtered_unused_policies | length }}
          
          policy_id,name,status,action,last_used,days_since_last_used,hit_count,bytes,packets,srcintf,dstintf,srcaddr,dstaddr,service,comments
          {% for policy in filtered_unused_policies %}
          {{ policy.policy_id }},"{{ policy.name | replace('"', '""') }}",{{ policy.status }},{{ policy.action }},{{ policy.last_used_readable }},{{ policy.days_since_last_used }},{{ policy.hit_count }},{{ policy.bytes }},{{ policy.packets }},"{{ policy.srcintf }}","{{ policy.dstintf }}","{{ policy.srcaddr }}","{{ policy.dstaddr }}","{{ policy.service }}","{{ policy.comments | replace('"', '""') }}"
          {% endfor %}
        dest: "{{ playbook_dir }}/artifacts/unused_policies_{{ ansible_date_time.epoch }}.csv"
      when: export_to_file | default(false) | bool

    - name: 生成清理CLI腳本
      copy:
        content: |
          # FortiGate Policy Cleanup Commands
          # Generated: {{ ansible_date_time.iso8601 }}
          # ⚠️ 請人工審查後執行，不會自動執行
          
          # === 停用長期未使用的Policy ===
          config firewall policy
          {% for policy in unused_long_term[:10] %}
              edit {{ policy.policy_id }}
                  set status disable
                  set comments "{{ policy.comments }} [DISABLED-{{ ansible_date_time.date }}-UNUSED-{{ policy.days_since_last_used }}DAYS]"
              next
          {% endfor %}
          end
          
          # === 從未使用的Policy（建議先停用觀察） ===
          config firewall policy
          {% for policy in unused_never[:5] %}
              # Policy {{ policy.policy_id }}: {{ policy.name }}
              # edit {{ policy.policy_id }}
              #     set status disable
              # next
          {% endfor %}
          end
        dest: "{{ playbook_dir }}/artifacts/cleanup_commands_{{ ansible_date_time.epoch }}.cli"
        mode: '0644'
      when: 
        - export_to_file | default(false) | bool
        - filtered_unused_policies | length > 0

    - name: 最終報告
      debug:
        msg: |
          ========= 查詢完成 =========
          找到 {{ filtered_unused_policies | length }} 個符合條件的Policy
          
          {% if export_to_file | default(false) | bool %}
          檔案已匯出到artifacts目錄：
          - unused_policies_{{ ansible_date_time.epoch }}.csv
          - cleanup_commands_{{ ansible_date_time.epoch }}.cli
          {% endif %}
          
          ⚠️ 請人工審查所有結果後再執行任何變更
          =========================
