---
- name: Query FortiGate Firewall Policies (Clean Version)
  hosts: localhost
  gather_facts: true
  vars:
    fortigate_api_url: "https://{{ fortigate_host }}:{{ fortigate_api_port | default('443') }}"

  tasks:
    # =================== 安全檢查 ===================
    - name: 安全提醒
      debug:
        msg: "🔍 開始查詢FortiGate Policy (只讀模式)"

    # =================== 資料收集階段 ===================
    - name: 查詢所有Firewall Policy設定
      uri:
        url: "{{ fortigate_api_url }}/api/v2/cmdb/firewall/{{ policy_type | default('policy') }}"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_access_token }}"
        body_format: form-urlencoded
        body:
          vdom: "{{ vdom_name | default('root') }}"
        validate_certs: "{{ fortigate_validate_certs | default(false) }}"
        timeout: "{{ fortigate_timeout | default('60') | int }}"
      register: policy_config_result
      retries: "{{ fortigate_api_retries | default('3') | int }}"
      delay: "{{ fortigate_api_delay | default('5') | int }}"

    - name: 顯示Policy查詢結果
      debug:
        msg: "✅ 找到 {{ policy_config_result.json.results | length }} 個Policy"

    # =================== 資料處理 ===================
    - name: 初始化變數
      set_fact:
        all_policies: "{{ policy_config_result.json.results | default([]) }}"
        total_policies: "{{ policy_config_result.json.results | length }}"

    - name: 計算Policy統計
      set_fact:
        enabled_count: "{{ all_policies | selectattr('status', 'equalto', 'enable') | list | length }}"
        disabled_count: "{{ all_policies | selectattr('status', 'equalto', 'disable') | list | length }}"

    # =================== 應用過濾條件（簡化版） ===================
    - name: 過濾Policy列表
      set_fact:
        filtered_policies: "{{ final_list }}"
      vars:
        exclude_ids: "{{ filter_options.exclude_policy_ids | default([]) | map('string') | list }}"
        min_id: "{{ filter_options.min_policy_id | default('') }}"
        max_id: "{{ filter_options.max_policy_id | default('') }}"
        final_list: |
          [
          {% for policy in all_policies %}
          {% set policy_id_str = policy.policyid | string %}
          {% set skip_policy = false %}
          
          {# 應用過濾條件 #}
          {% if exclude_ids and policy_id_str in exclude_ids %}
          {% set skip_policy = true %}
          {% endif %}
          
          {% if min_id != '' and policy.policyid | int < min_id | int %}
          {% set skip_policy = true %}
          {% endif %}
          
          {% if max_id != '' and policy.policyid | int > max_id | int %}
          {% set skip_policy = true %}
          {% endif %}
          
          {% if not include_disabled | default(false) and policy.status | default('enable') != 'enable' %}
          {% set skip_policy = true %}
          {% endif %}
          
          {% if not skip_policy %}
          {
            "policy_id": "{{ policy.policyid }}",
            "name": "{{ policy.name | default('Policy_' + (policy.policyid | string)) }}",
            "status": "{{ policy.status | default('enable') }}",
            "action": "{{ policy.action | default('accept') }}",
            "srcintf": "{{ policy.srcintf | default([]) | join(',') }}",
            "dstintf": "{{ policy.dstintf | default([]) | join(',') }}",
            "srcaddr": "{{ policy.srcaddr | default([]) | join(',') }}",
            "dstaddr": "{{ policy.dstaddr | default([]) | join(',') }}",
            "service": "{{ policy.service | default([]) | join(',') }}",
            "logtraffic": "{{ policy.logtraffic | default('disable') }}",
            "comments": "{{ policy.comments | default('') }}",
            "is_enabled": {{ policy.status | default('enable') == 'enable' }}
          }{% if not loop.last %},{% endif %}
          {% endif %}
          {% endfor %}
          ]

    # =================== 結果摘要 ===================
    - name: 顯示分析摘要
      debug:
        msg: |
          ========= FortiGate Policy 分析摘要 =========
          VDOM: {{ vdom_name | default('root') }}
          查詢時間: {{ ansible_date_time.iso8601 }}
          
          📊 統計結果:
          - 總Policy數量: {{ total_policies }}
          - 啟用的Policy: {{ enabled_count }}
          - 停用的Policy: {{ disabled_count }}
          - 符合過濾條件: {{ filtered_policies | length }}
          
          🔍 過濾設定:
          {% if filter_options.exclude_policy_ids | default([]) | length > 0 %}
          - 排除Policy ID: {{ filter_options.exclude_policy_ids | join(', ') }}
          {% endif %}
          {% if filter_options.min_policy_id | default('') != '' %}
          - 最小Policy ID: {{ filter_options.min_policy_id }}
          {% endif %}
          {% if filter_options.max_policy_id | default('') != '' %}
          - 最大Policy ID: {{ filter_options.max_policy_id }}
          {% endif %}
          - 包含停用Policy: {{ include_disabled | default(false) }}
          ==========================================

    # =================== 顯示Policy清單 ===================
    - name: 顯示Policy清單摘要
      debug:
        msg: |
          ========= Policy 清單摘要 (前10筆) =========
          {% for policy in filtered_policies[:10] %}
          {{ "%2d" | format(loop.index) }}. Policy {{ policy.policy_id }}: {{ policy.name[:35] }}
              狀態: {{ policy.status }} | 動作: {{ policy.action }}
              來源: {{ policy.srcaddr[:40] }}{{ '...' if policy.srcaddr | length > 40 else '' }}
              目的: {{ policy.dstaddr[:40] }}{{ '...' if policy.dstaddr | length > 40 else '' }}
              服務: {{ policy.service[:25] }}{{ '...' if policy.service | length > 25 else '' }}
          {% endfor %}
          {% if filtered_policies | length > 10 %}
          
          ... 還有 {{ filtered_policies | length - 10 }} 筆Policy
          {% endif %}
          =======================================
      when: filtered_policies | length > 0

    # =================== CSV內容輸出 ===================
    - name: 完整CSV內容
      debug:
        msg: |
          ========= 完整CSV內容 =========
          
          ## 建議檔名: fortigate_policies_{{ ansible_date_time.epoch }}.csv
          
          policy_id,name,status,action,srcintf,dstintf,srcaddr,dstaddr,service,logtraffic,comments
          {% for policy in filtered_policies %}
          {{ policy.policy_id }},"{{ policy.name | replace('"', '""') }}",{{ policy.status }},{{ policy.action }},"{{ policy.srcintf }}","{{ policy.dstintf }}","{{ policy.srcaddr }}","{{ policy.dstaddr }}","{{ policy.service }}",{{ policy.logtraffic }},"{{ policy.comments | replace('"', '""') }}"
          {% endfor %}
          
          ========= CSV內容結束 =========
          
          使用方法:
          1. 複製上述CSV內容
          2. 開啟Excel或記事本
          3. 貼上內容並儲存為.csv檔案
      when: 
        - filtered_policies | length > 0
        - show_csv | default(true) | bool

    # =================== 詳細報告輸出 ===================
    - name: 詳細分析報告
      debug:
        msg: |
          ========= 詳細分析報告 =========
          
          ## 基本資訊
          - 報告生成時間: {{ ansible_date_time.iso8601 }}
          - FortiGate主機: {{ fortigate_host }}
          - VDOM: {{ vdom_name | default('root') }}
          
          ## 統計摘要
          - 總Policy數量: {{ total_policies }}
          - 啟用Policy: {{ enabled_count }} ({{ (enabled_count|int * 100 / total_policies|int) | round(1) }}%)
          - 停用Policy: {{ disabled_count }} ({{ (disabled_count|int * 100 / total_policies|int) | round(1) }}%)
          - 本次分析: {{ filtered_policies | length }} 個Policy
          
          ## Policy詳細資訊
          {% for policy in filtered_policies %}
          
          {{ loop.index }}. Policy {{ policy.policy_id }}: {{ policy.name }}
             - 狀態: {{ policy.status }}
             - 動作: {{ policy.action }}
             - 來源介面: {{ policy.srcintf }}
             - 目的介面: {{ policy.dstintf }}
             - 來源地址: {{ policy.srcaddr }}
             - 目的地址: {{ policy.dstaddr }}
             - 服務: {{ policy.service }}
             - 記錄流量: {{ policy.logtraffic }}
             - 備註: {{ policy.comments }}
          {% endfor %}
          
          ## 建議管理命令
          
          ### 備份設定
          execute backup config management-station comment "policy-analysis-{{ ansible_date_time.date }}"
          
          ### Policy管理範例 (請根據需要修改)
          config firewall policy
          {% for policy in filtered_policies[:5] %}
          {% if policy.status == 'enable' %}
              # Policy {{ policy.policy_id }}: {{ policy.name }}
              # 用途檢查 - 來源: {{ policy.srcaddr }} -> 目的: {{ policy.dstaddr }}
              # edit {{ policy.policy_id }}
              #     set status disable
              #     set comments "{{ policy.comments }} [ANALYSIS-{{ ansible_date_time.date }}]"
              # next
          {% endif %}
          {% endfor %}
          end
          
          ## 注意事項
          ⚠️ 所有Policy變更請在維護時間窗口執行
          ⚠️ 建議先停用觀察，確認無影響後再考慮刪除
          ⚠️ 務必保留變更記錄以便回復
          
          ========= 報告結束 =========
      when: 
        - filtered_policies | length > 0
        - show_detailed_report | default(true) | bool

    # =================== 管理腳本輸出 ===================
    - name: 管理腳本
      debug:
        msg: |
          ========= FortiGate管理腳本 =========
          
          ## 建議檔名: fortigate_management_{{ ansible_date_time.epoch }}.cli
          
          # FortiGate Policy管理腳本
          # 生成時間: {{ ansible_date_time.iso8601 }}
          # 
          # 使用前請務必:
          # 1. 備份現有設定
          # 2. 在測試環境驗證
          # 3. 選擇適當的維護時間窗口
          
          # === 系統資訊檢查 ===
          get system status
          get system performance status
          
          # === 設定備份 ===
          execute backup config management-station comment "before-policy-changes-{{ ansible_date_time.date }}"
          
          # === Policy檢查命令 ===
          show firewall policy
          diagnose firewall iprope show 100000
          
          # === Policy停用範例 (請根據分析結果選擇執行) ===
          config firewall policy
          {% for policy in filtered_policies[:10] %}
          {% if policy.status == 'enable' %}
              # Policy {{ policy.policy_id }}: {{ policy.name }}
              # 檢查項目: {{ policy.srcaddr }} -> {{ policy.dstaddr }} ({{ policy.service }})
              # 建議: 先停用觀察30天，確認無影響後決定是否刪除
              # 
              # edit {{ policy.policy_id }}
              #     set status disable
              #     set comments "{{ policy.comments }} [DISABLED-{{ ansible_date_time.date }}-FOR-REVIEW]"
              # next
              # 
          {% endif %}
          {% endfor %}
          end
          
          # === 驗證命令 ===
          show firewall policy | grep disable
          
          # === 監控建議 ===
          # 1. 觀察系統log: execute log display
          # 2. 檢查網路連線是否正常
          # 3. 確認應用服務運作狀況
          # 4. 收集使用者回饋
          
          ========= 腳本結束 =========
      when: 
        - filtered_policies | length > 0
        - show_management_script | default(true) | bool

    # =================== 最終報告 ===================
    - name: 任務完成報告
      debug:
        msg: |
          🎯 FortiGate Policy分析完成！
          
          📊 執行摘要:
          - 查詢了 {{ total_policies }} 個Policy
          - 分析了 {{ filtered_policies | length }} 個符合條件的Policy
          - 啟用狀態: {{ enabled_count }} 個
          - 停用狀態: {{ disabled_count }} 個
          
          📋 已提供內容:
          {% if show_csv | default(true) %}✅ CSV格式資料 (可匯入Excel){% else %}❌ CSV輸出已停用{% endif %}
          {% if show_detailed_report | default(true) %}✅ 詳細分析報告{% else %}❌ 詳細報告已停用{% endif %}
          {% if show_management_script | default(true) %}✅ 管理CLI腳本{% else %}❌ 管理腳本已停用{% endif %}
          
          💡 使用建議:
          1. 複製需要的內容到檔案中儲存
          2. 仔細審查每個Policy的必要性
          3. 制定分階段的清理計劃
          4. 在維護時間窗口執行變更
          
          ⚠️ 安全提醒:
          - 所有變更都需要人工確認
          - 建議先在測試環境驗證
          - 務必準備好回復計劃
