---
- name: Set FortiGate DHCP Reserved Address
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # --- 請在 AWX Job Template 的 Extra Variables 中傳入以下參數 ---
    # target_ip: "192.168.250.103"
    # target_mac: "00:25:aa:aa:01:03"
    # target_description: "test103_PC_updated"
    dhcp_server_id: "{{ server_id | default('3') }}"

  tasks:
    - name: 1. 獲取所有現有的 DHCP 保留位址
      ansible.builtin.uri:
        url: "https://{{ lookup('env', 'FORTIGATE_HOST') }}/api/v2/cmdb/system.dhcp/server/{{ dhcp_server_id }}/reserved-address"
        method: GET
        headers:
          Authorization: "Bearer {{ lookup('env', 'FORTIGATE_API_TOKEN') }}"
        validate_certs: false
        status_code: 200
      register: existing_reservations

    # --- 資料處理與變數設定 ---
    - name: 2. 處理資料 - 尋找目標與衝突物件
      ansible.builtin.set_fact:
        # 使用 selectattr 篩選出 IP 符合 target_ip 的物件列表
        target_objects: "{{ existing_reservations.json.results | selectattr('ip', 'equalto', target_ip) | list }}"
        # 關鍵修正：使用 'where' 過濾器和 'lower' 方法來實現忽略大小寫的比較
        conflicting_objects: "{{ existing_reservations.json.results | where('item.mac.lower() == target_mac.lower()') | list }}"

    # --- 檢查點 ---
    - name: 3. 檢查點：確認目標 IP 是否存在
      ansible.builtin.fail:
        msg: "錯誤：在 DHCP Server {{ dhcp_server_id }} 中找不到目標 IP 位址 '{{ target_ip }}'。請確認 IP 是否正確。"
      when: target_objects | length == 0

    - name: 4. 檢查點：檢查 MAC 位址是否與其他設定衝突
      ansible.builtin.fail:
        msg: |
          錯誤：執行停止。您提供的 MAC 位址 '{{ target_mac }}' 已被現有設定中的另一個物件使用。
          衝突物件 IP: {{ conflicting_objects[0].ip }}
          衝突物件描述: {{ conflicting_objects[0].description | default('N/A', true) }}
          請更換 MAC 位址後再試。
      # 條件：
      # 1. 找到了 MAC 衝突的物件 (conflicting_objects 列表不為空)
      # 2. 且該衝突物件的 IP 與我們的目標 IP 不同
      when:
        - conflicting_objects | length > 0
        - conflicting_objects[0].ip != target_ip

    # --- 執行更新 ---
    - name: 5. 如果找到物件，則執行更新
      vars:
        # 從列表中取出第一個 (也是唯一一個) 物件的 ID
        target_object_id: "{{ target_objects[0].id }}"
      ansible.builtin.uri:
        # API 路徑需要包含物件的 ID
        url: "https://{{ lookup('env', 'FORTIGATE_HOST') }}/api/v2/cmdb/system.dhcp/server/{{ dhcp_server_id }}/reserved-address/{{ target_object_id }}"
        method: PUT
        headers:
          Authorization: "Bearer {{ lookup('env', 'FORTIGATE_API_TOKEN') }}"
        body:
          # 在 body 中提供要更新的欄位
          mac: "{{ target_mac }}"
          description: "{{ target_description }}"
        body_format: json
        validate_certs: false
        status_code: 200
      register: update_result

    - name: 6. 顯示更新成功訊息
      ansible.builtin.debug:
        msg:
          - "成功更新 DHCP 保留位址！"
          - "  目標 IP: {{ target_ip }}"
          - "  更新後 MAC: {{ target_mac }}"
          - "  更新後描述: {{ target_description }}"
      when: update_result is defined and update_result.changed
