---
# =============================================================================
# FortiGate DHCP Reserved Address Create&Update Execute v1.0
# 用途：執行實際的DHCP Reserved Address創建或更新操作
# 功能：根據Preview結果執行CREATE或UPDATE操作
# 輸入：接收Preview步驟的workflow變數
# 輸出：執行結果和操作摘要
# 版本：v1.0 - 統一設計架構，優化輸出格式
# =============================================================================

- name: FortiGate DHCP Reserved Create&Update Execute For Workflow v1.0
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    # 接收workflow變數 - 目標配置
    target_ip: "{{ wf_target_ip }}"
    target_mac: "{{ wf_target_mac }}"
    target_description: "{{ wf_target_description }}"
    server_id: "{{ wf_server_id }}"
    
    # 接收workflow變數 - 操作控制
    operation_type: "{{ wf_operation_type }}"
    needs_operation: "{{ (wf_needs_operation | default('false')) | bool }}"
    existing_object: "{{ (wf_existing_object | default('{}')) | from_json }}"
    
    # 接收workflow變數 - 系統資訊
    server_info: "{{ (wf_server_info | default('{}')) | from_json }}"
    backup_info: "{{ (wf_backup_info | default('{}')) | from_json }}"
    preview_version: "{{ wf_preview_version | default('unknown') }}"
    
    # FortiGate連接參數
    fortigate_host: "{{ fortigate_host }}"
    fortigate_token: "{{ fortigate_access_token }}"
    api_retries: "{{ fortigate_api_retries | default('3') | int }}"
    api_delay: "{{ fortigate_api_delay | default('5') | int }}"
    connection_timeout: "{{ fortigate_timeout | default('30') | int }}"
    validate_certs: "{{ fortigate_validate_certs | default(false) | bool }}"
    
  tasks:
    # ==================== 參數驗證區塊 ====================
    - name: "🔍 Validate Workflow Parameters"
      ansible.builtin.fail:
        msg: |
          ❌ 從Workflow接收參數失敗！缺少關鍵參數
          
          此Job Template僅應在Workflow中執行
          請確認Preview步驟已正確完成
      when: 
        - target_ip is not defined or 
          target_mac is not defined or
          operation_type is not defined or
          preview_version is not defined

    - name: "🔍 Validate FortiGate Credentials"
      ansible.builtin.fail:
        msg: |
          ❌ 缺少FortiGate Credential參數！
          
          請確認Job Template已正確設定Credential
          檢查項目:
          - FortiGate Host
          - API Access Token
      when: 
        - fortigate_host is not defined or 
          fortigate_access_token is not defined

    # ==================== API 連接驗證 ====================
    - name: "🔌 Test FortiGate API Connection"
      ansible.builtin.uri:
        url: "https://{{ fortigate_host }}/api/v2/cmdb/system/global"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_token }}"
        validate_certs: "{{ validate_certs }}"
        status_code: 200
        timeout: "{{ connection_timeout }}"
      register: api_connection_test
      retries: "{{ api_retries }}"
      delay: "{{ api_delay }}"

    - name: "✅ API Connection Established"
      ansible.builtin.debug:
        msg: "✅ API連線成功 | FortiGate版本: {{ fortigate_version }}"
      vars:
        fortigate_version: "{{ api_connection_test.json.results.version | default(api_connection_test.json.version | default('未知')) }}"

    # ==================== 執行資訊顯示 ====================
    - name: "📋 Execution Information Header"
      ansible.builtin.debug:
        msg: "==================== FortiGate DHCP Reserved Create&Update Execute v1.0 ===================="

    - name: "🚀 Execute Parameters Summary"
      ansible.builtin.debug:
        msg: "🚀 Create&Update執行模式 | 已通過人工確認 | 操作類型: {{ operation_type }} | 需要執行: {{ needs_operation }} | IP: {{ target_ip }} | MAC: {{ target_mac }}"

    - name: "📊 Operations Overview"
      ansible.builtin.debug:
        msg: "📊 操作概覽 | DHCP Server: {{ server_info.dhcp_description | default('N/A') }} | 描述: {{ target_description }}"

    # ==================== 無需操作處理 ====================
    - name: "ℹ️ No Operation Required"
      ansible.builtin.debug:
        msg: |
          ℹ️ 配置已是最新狀態，無需執行任何操作
          
          當前配置:
          - IP地址: {{ target_ip }}
          - MAC地址: {{ target_mac }}
          - 描述: {{ target_description }}
      when: not needs_operation

    # ==================== 執行前驗證區塊 ====================
    - name: "🔍 Pre-execution Verification Section Header"
      ansible.builtin.debug:
        msg: "==================== 執行前驗證 ===================="
      when: needs_operation

    - name: "🔍 Verify Current Configuration State"
      ansible.builtin.uri:
        url: "https://{{ fortigate_host }}/api/v2/cmdb/system.dhcp/server/{{ server_id }}/reserved-address{{ '/' + (existing_object.id | string) if operation_type == 'UPDATE' else '' }}"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_token }}"
        validate_certs: "{{ validate_certs }}"
        status_code: [200, 404]
        timeout: "{{ connection_timeout }}"
      register: pre_execution_verification
      retries: "{{ api_retries }}"
      delay: "{{ api_delay }}"
      when: needs_operation

    # UPDATE 模式的一致性檢查
    - name: "🔍 UPDATE Configuration Consistency Check"
      ansible.builtin.set_fact:
        config_consistent: "{{ 
          (pre_execution_verification.json.results | first).ip == existing_object.ip and 
          (pre_execution_verification.json.results | first).mac.lower() == existing_object.mac.lower() 
        }}"
      when: 
        - needs_operation
        - operation_type == "UPDATE"
        - pre_execution_verification.status == 200

    - name: "❌ Configuration Changed During Review"
      ansible.builtin.fail:
        msg: |
          ❌ 配置在審核期間已被修改
          
          檢測到配置不一致:
          - 原始IP: {{ existing_object.ip }}
          - 原始MAC: {{ existing_object.mac }}
          
          解決方案: 請重新執行Preview步驟確認最新狀態
      when: 
        - needs_operation
        - operation_type == "UPDATE"
        - pre_execution_verification.status == 200
        - not config_consistent

    # ==================== CREATE 操作執行區塊 ====================
    - name: "🆕 CREATE Operation Section Header"
      ansible.builtin.debug:
        msg: "==================== CREATE 操作執行 ===================="
      when: 
        - needs_operation
        - operation_type == "CREATE"

    - name: "🔧 Execute CREATE Operation"
      ansible.builtin.uri:
        url: "https://{{ fortigate_host }}/api/v2/cmdb/system.dhcp/server/{{ server_id }}/reserved-address"
        method: POST
        headers:
          Authorization: "Bearer {{ fortigate_token }}"
        body:
          ip: "{{ target_ip }}"
          mac: "{{ target_mac }}"
          description: "{{ target_description }}"
        body_format: json
        validate_certs: "{{ validate_certs }}"
        status_code: 200
        timeout: "{{ connection_timeout }}"
      register: create_result
      retries: "{{ api_retries }}"
      delay: "{{ api_delay }}"
      when: 
        - needs_operation
        - operation_type == "CREATE"

    - name: "🎉 CREATE Operation Success"
      ansible.builtin.debug:
        msg: |
          ✅ CREATE操作成功完成
          
          配置詳情:
          - IP地址: {{ target_ip }}
          - MAC地址: {{ target_mac }}
          - 描述: {{ target_description }}
          - DHCP Server: {{ server_id }}
      when: 
        - needs_operation
        - operation_type == "CREATE"
        - create_result.status == 200

    - name: "❌ CREATE Operation Failed"
      ansible.builtin.fail:
        msg: |
          ❌ CREATE操作失敗
          
          錯誤詳情:
          - HTTP狀態: {{ create_result.status | default('未知') }}
          - 錯誤訊息: {{ create_result.json.cli_error | default([create_result.msg | default('未知')]) | join(', ') }}
          
          請檢查:
          1. IP地址是否在DHCP範圍內
          2. MAC地址格式是否正確
          3. 是否有重複配置
      when: 
        - needs_operation
        - operation_type == "CREATE"
        - create_result.status != 200

    # ==================== UPDATE 操作執行區塊 ====================
    - name: "🔄 UPDATE Operation Section Header"
      ansible.builtin.debug:
        msg: "==================== UPDATE 操作執行 ===================="
      when: 
        - needs_operation
        - operation_type == "UPDATE"

    - name: "🔧 Execute UPDATE Operation"
      ansible.builtin.uri:
        url: "https://{{ fortigate_host }}/api/v2/cmdb/system.dhcp/server/{{ server_id }}/reserved-address/{{ existing_object.id | string }}"
        method: PUT
        headers:
          Authorization: "Bearer {{ fortigate_token }}"
        body:
          ip: "{{ target_ip }}"
          mac: "{{ target_mac }}"
          description: "{{ target_description }}"
        body_format: json
        validate_certs: "{{ validate_certs }}"
        status_code: 200
        timeout: "{{ connection_timeout }}"
      register: update_result
      retries: "{{ api_retries }}"
      delay: "{{ api_delay }}"
      when: 
        - needs_operation
        - operation_type == "UPDATE"

    - name: "🎉 UPDATE Operation Success"
      ansible.builtin.debug:
        msg: |
          ✅ UPDATE操作成功完成
          
          配置詳情:
          - 配置ID: {{ existing_object.id | string }}
          - IP地址: {{ target_ip }}
          - MAC地址: {{ target_mac }}
          - 描述: {{ target_description }}
      when: 
        - needs_operation
        - operation_type == "UPDATE"
        - update_result.status == 200

    - name: "❌ UPDATE Operation Failed"
      ansible.builtin.fail:
        msg: |
          ❌ UPDATE操作失敗
          
          錯誤詳情:
          - 配置ID: {{ existing_object.id | string }}
          - HTTP狀態: {{ update_result.status | default('未知') }}
          - 錯誤訊息: {{ update_result.json.cli_error | default([update_result.msg | default('未知')]) | join(', ') }}
          
          請檢查:
          1. 配置是否仍然存在
          2. MAC地址格式是否正確
          3. 權限是否充足
      when: 
        - needs_operation
        - operation_type == "UPDATE"
        - update_result.status != 200

    # ==================== 操作後驗證區塊 ====================
    - name: "🔍 Post-execution Verification Section Header"
      ansible.builtin.debug:
        msg: "==================== 操作後驗證 ===================="
      when: needs_operation

    - name: "🔍 Verify Operation Result"
      ansible.builtin.uri:
        url: "https://{{ fortigate_host }}/api/v2/cmdb/system.dhcp/server/{{ server_id }}/reserved-address?filter=ip=={{ target_ip }}"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_token }}"
        validate_certs: "{{ validate_certs }}"
        status_code: 200
        timeout: "{{ connection_timeout }}"
      register: post_verification
      retries: "{{ api_retries }}"
      delay: "{{ api_delay }}"
      when: 
        - needs_operation
        - (create_result.status == 200 if operation_type == 'CREATE' else update_result.status == 200)

- name: "✅ Operation Verification Result"
      ansible.builtin.debug:
        msg: "✅ 操作驗證通過 | 找到配置: {{ post_verification.json.results | length }} 筆 | 當前MAC: {{ (post_verification.json.results | first).mac }} | 當前描述: {{ (post_verification.json.results | first).description }}"
      when: 
        - needs_operation
        - post_verification is defined
        - post_verification.json.results | length > 0

    # ==================== 最終摘要區塊 ====================
    - name: "📊 Final Summary Section Header"
      ansible.builtin.debug:
        msg: "==================== 最終摘要 ===================="

    - name: "📊 Operation Results Summary"
      ansible.builtin.debug:
        msg: |
          📊 {{ operation_type }}操作結果摘要
          
          基本資訊:
          - IP地址: {{ target_ip }}
          - MAC地址: {{ target_mac }}
          - 執行狀態: {{ operation_status }}
          
          {% if needs_operation and operation_type == 'CREATE' and create_result.status == 200 %}
          ✅ 新配置已成功創建
          {% elif needs_operation and operation_type == 'UPDATE' and update_result.status == 200 %}
          ✅ 既有配置已成功更新
          {% elif not needs_operation %}
          ℹ️ 配置已是最新狀態，無需變更
          {% else %}
          ❌ 操作執行失敗，請檢查錯誤訊息
          {% endif %}
      vars:
        operation_status: >-
          {%- if not needs_operation -%}
            ℹ️無需變更
          {%- elif operation_type == 'CREATE' and create_result.status == 200 -%}
            ✅創建成功
          {%- elif operation_type == 'UPDATE' and update_result.status == 200 -%}
            ✅更新成功
          {%- else -%}
            ❌操作失敗
          {%- endif -%}

    - name: "📊 Configuration Details"
      ansible.builtin.debug:
        msg: |
          📊 配置環境資訊
          
          DHCP Server: {{ server_id }} ({{ server_info.dhcp_description | default('N/A') }})
          描述資訊: {{ target_description }}
          {% if backup_info.timestamp is defined %}
          備份時間: {{ backup_info.timestamp }}
          {% endif %}

    - name: "📅 Completion Information"
      ansible.builtin.debug:
        msg: "📅 完成時間: {{ ansible_date_time.iso8601 }} | 版本: v1.0"
